/* GENERATED by tools/merge_tw_config.js - merged from 0 inline page configs. */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './*/*.html', './assets/*.js'],
  theme: {
    extend: {
      colors: {
            "brand": {
                  "50": "#f0fdf4",
                  "100": "#dcfce7",
                  "400": "#4ade80",
                  "500": "#22c55e",
                  "600": "#16a34a",
                  "900": "#14532d"
            }
      },
      animation: {
            "grid-flow": "grid-move 20s linear infinite",
            "fade-in": "fadeIn 0.5s ease-out forwards",
            "pulse-fast": "pulse 0.2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
            "slide-batch": "slideBatch 1.5s ease-in-out forwards",
            "bounce-slow": "bounce 2s infinite",
            "gradient-flow": "gradientFlow 2s linear infinite",
            "slide-up": "slideUp 0.4s ease-out forwards",
            "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
            "cursor-blink": "blink 1s infinite",
            "bounce-slight": "bounceSlight 2s infinite"
      },
      keyframes: {
            "grid-move": {
                  "0%": {
                        "backgroundPosition": "0 0"
                  },
                  "100%": {
                        "backgroundPosition": "40px 40px"
                  }
            },
            "fadeIn": {
                  "0%": {
                        "opacity": "0",
                        "transform": "translateY(10px)"
                  },
                  "100%": {
                        "opacity": "1",
                        "transform": "translateY(0)"
                  }
            },
            "slideBatch": {
                  "0%": {
                        "transform": "translateX(0) scale(1)",
                        "opacity": "1"
                  },
                  "50%": {
                        "transform": "translateX(100px) scale(0.8)",
                        "opacity": "0.5"
                  },
                  "100%": {
                        "transform": "translateX(200px) scale(0)",
                        "opacity": "0"
                  }
            },
            "gradientFlow": {
                  "0%": {
                        "backgroundPosition": "100% 0"
                  },
                  "100%": {
                        "backgroundPosition": "-100% 0"
                  }
            },
            "slideUp": {
                  "0%": {
                        "opacity": "0",
                        "transform": "translateY(20px)"
                  },
                  "100%": {
                        "opacity": "1",
                        "transform": "translateY(0)"
                  }
            },
            "blink": {
                  "0%, 50%": {
                        "opacity": "1"
                  },
                  "51%, 100%": {
                        "opacity": "0"
                  }
            },
            "bounceSlight": {
                  "0%, 100%": {
                        "transform": "translateY(0)"
                  },
                  "50%": {
                        "transform": "translateY(-5px)"
                  }
            }
      },
    },
  },
  plugins: [],
};
