#!/usr/bin/env python3
"""Lift the article's opening section above the visualisation.

Measured, the first real paragraph on a module page started around 1270px down
- roughly two screens, behind the control panel, the plot and the readouts.
Anyone skimming the page sees a tool and no prose, which is exactly the reading
the AdSense review took.

This moves the article's first section up between the lead paragraph and the
widget, and adds a short contents list for the rest. Nothing is duplicated: the
section is *moved*, and a slot marker is left where it came from so a rebuild
can put it back before recomputing. That keeps the step idempotent on the
hand-written pages, whose articles no other generator rewrites.

Runs after build_articles.py (it needs the finished article) and after
build_seo.py (it anchors on the byline block).
"""

import html
import os
import re
import sys

from build_articles import DIV, _close, card_inner
from lib_catalog import ROOT, modules

BEGIN = "<!-- VIZLEARN:LEDE:BEGIN (generated by tools/build_lede.py) -->"
END = "<!-- VIZLEARN:LEDE:END -->"
# The leading \s* matters: the block is inserted after a newline, and a restore
# that left it behind grew the file by a byte on every build.
BLOCK = re.compile(r"\s*" + re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

# Wraps the moved section inside the generated block, so a rebuild can lift it
# back out and drop it into the slot it came from.
SRC_BEGIN = "<!-- VIZLEARN:LEDE:SRC -->"
SRC_END = "<!-- VIZLEARN:LEDE:/SRC -->"
SRC = re.compile(re.escape(SRC_BEGIN) + r"(.*?)" + re.escape(SRC_END), re.S)
SLOT = "<!-- VIZLEARN:LEDE:SLOT -->"

LEAD = re.compile(r"<!-- VIZLEARN:BYLINE:END -->\s*<p\b[^>]*>.*?</p>", re.S)
H3 = re.compile(r"<h3\b([^>]*)>(.*?)</h3>", re.S)
TAGS = re.compile(r"<[^>]+>")

# Headings that label the visualisation's own furniture rather than prose. A
# section under one of these is a control legend, not an introduction.
UI_HEADINGS = {
    "controls", "parameters", "visualization", "visualisation", "legend",
    "algorithm insight", "insight", "output", "settings", "canvas view",
    "internal flow", "tree metrics", "how to use", "instructions",
}


def text_of(fragment):
    return re.sub(r"\s+", " ", html.unescape(TAGS.sub(" ", fragment))).strip()


def slug(s):
    s = re.sub(r"[^a-z0-9]+", "-", text_of(s).lower()).strip("-")
    return "vz-s-" + (s[:48] or "section")


def unique_slugs(titles):
    """One id per heading, de-duplicated within the page.

    A generated page can carry the same heading twice: the walkthrough folds a
    step in under its own title, and the article may discuss the same thing
    later. Emitting slug(title) for both produced two elements with one id -
    invalid HTML, and a contents entry whose link jumped to the wrong section.
    """
    seen, out = {}, []
    for t in titles:
        base = slug(t)
        seen[base] = seen.get(base, 0) + 1
        out.append(base if seen[base] == 1 else "%s-%d" % (base, seen[base]))
    return out


def top_level_divs(src, start, end):
    """(open_start, close_end) for each <div> directly inside [start, end)."""
    out = []
    i = start
    while i < end:
        m = re.compile(r"<div\b[^>]*>", re.I).search(src, i, end)
        if not m:
            break
        close_start, close_end = _close(src, m.start(), DIV)
        if close_start == -1 or close_end > end:
            break
        out.append((m.start(), close_end))
        i = close_end
    return out


def segments(src, start, end):
    """Split an article body into (start, end, heading) sections.

    Two shapes exist on the site. Most pages wrap each section in its own div;
    the older machine-learning pages put a single `.prose` wrapper around a
    lead paragraph and a flat run of h3 siblings. Handle both, and report any
    substantial text before the first heading as a preamble - on the flat pages
    that opening paragraph is the best lede available.
    """
    divs = top_level_divs(src, start, end)
    if len(divs) >= 3 and all(len(H3.findall(src[a:b])) == 1 for a, b in divs):
        out = []
        for a, b in divs:
            m = H3.search(src, a, b)
            out.append((a, b, text_of(m.group(2)) if m else ""))
        return None, out

    # Flat: segment on the headings themselves, inside the single wrapper.
    if len(divs) == 1:
        m = re.compile(r"<div\b[^>]*>", re.I).match(src, divs[0][0])
        start, end = m.end(), divs[0][1] - len("</div>")

    heads = [m for m in H3.finditer(src, start, end)]
    if not heads:
        return None, []
    preamble = (start, heads[0].start())
    out = []
    for i, m in enumerate(heads):
        stop = heads[i + 1].start() if i + 1 < len(heads) else end
        out.append((m.start(), stop, text_of(m.group(2))))
    return preamble, out


def article_body(src):
    """(start, end) of the div holding the article's sections."""
    span = card_inner(src)
    if not span:
        return None
    # inside the card: a header div, then the body div holding the sections
    for open_start, close_end in top_level_divs(src, span[0], span[1]):
        if H3.search(src, open_start, close_end):
            m = re.compile(r"<div\b[^>]*>", re.I).match(src, open_start)
            return m.end(), close_end - len("</div>")
    return None


def restore(src):
    """Undo a previous run: put the moved section back in its slot."""
    m = BLOCK.search(src)
    if not m:
        return src
    inner = SRC.search(m.group(0))
    moved = inner.group(1) if inner else ""
    src = src[: m.start()] + src[m.end():]
    if SLOT in src:
        src = src.replace(SLOT, moved, 1)
    return src


def render(moved, headings):
    """The above-the-fold block: the opening section, then a contents list."""
    toc = ""
    if len(headings) >= 3:
        items = "".join(
            '<li><a href="#%s">%s</a></li>' % (i, html.escape(t)) for i, t in headings
        )
        toc = (
            '<nav class="vz-lede-toc" aria-labelledby="vz-lede-toc-h">'
            '<h2 id="vz-lede-toc-h">In this guide</h2>'
            "<ol>%s</ol></nav>" % items
        )
    return (
        BEGIN
        + '<section class="vz-lede" aria-labelledby="vz-lede-h">'
        + '<h2 id="vz-lede-h" class="vz-lede-h">Overview</h2>'
        # The wrapper is a grid area, so the prose and the contents can sit
        # side by side on a wide screen instead of stacking.
        + '<div class="vz-lede-body">'
        + SRC_BEGIN + moved + SRC_END
        + "</div>"
        + toc
        + "</section>"
        + END
    )


def process(rel):
    path = os.path.join(ROOT, rel)
    original = open(path, encoding="utf-8").read()
    src = restore(original)

    def bail(reason):
        """Give up on this page, but do not leave a stale block behind.

        A page can stop qualifying - a short new opening section pushes the
        old one below the 45-word floor, say. restore() has already lifted
        the previous run's block out of `src`; without writing that back the
        page keeps a contents list linking to ids this run never injects,
        which is how four hand-written pages ended up with dead anchors.
        """
        if src != original:
            open(path, "w", encoding="utf-8").write(src)
        return reason

    body = article_body(src)
    if not body:
        return bail("no-article")

    preamble, blocks = segments(src, *body)
    if len(blocks) < 3:
        return bail("too-few-sections")

    # Give every heading a stable id so the contents list can link to it.
    # Patch back to front so the offsets ahead of each edit stay valid.
    slugs = unique_slugs([t for _, _, t in blocks])
    for i in range(len(blocks) - 1, -1, -1):
        a, b, title = blocks[i]
        m = H3.search(src, a, b)
        if not m or "id=" in m.group(1):
            continue
        patched = '<h3%s id="%s">%s</h3>' % (m.group(1), slugs[i], m.group(2))
        src = src[: m.start()] + patched + src[m.end():]

    # Every id inserted above shifted the bytes after it, so the spans measured
    # before the patch no longer describe this string. Re-measure. Slicing with
    # the stale offsets silently truncated the section being moved.
    body = article_body(src)
    if not body:
        return bail("no-article")
    preamble, blocks = segments(src, *body)
    if len(blocks) < 3:
        return bail("too-few-sections")
    ids = list(zip(unique_slugs([t for _, _, t in blocks]),
                   [t for _, _, t in blocks]))

    # Prefer a substantial opening paragraph; otherwise lift the first section.
    if preamble and len(text_of(src[preamble[0]:preamble[1]]).split()) >= 45:
        first_start, first_end = preamble
        rest = [i for i in ids if i]
    else:
        first_start, first_end, title = blocks[0]
        first_end = blocks[0][1]
        if title.lower().rstrip(":?") in UI_HEADINGS:
            return bail("not-prose")
        rest = [i for i in ids[1:] if i]

    first = src[first_start:first_end]
    # A list-led section is still an introduction; only length disqualifies it.
    if len(text_of(first).split()) < 45:
        return bail("not-prose")

    src = src[:first_start] + SLOT + src[first_end:]
    block = render(first, rest)

    lead = LEAD.search(src)
    if not lead:
        return bail("no-anchor")
    src = src[: lead.end()] + "\n" + block + src[lead.end():]

    open(path, "w", encoding="utf-8").write(src)
    return "ok"


def main():
    counts = {}
    for m in modules():
        r = process(m["path"])
        counts[r] = counts.get(r, 0) + 1
    for k in sorted(counts):
        print("  %-18s %d" % (k, counts[k]))
    print("lede blocks written : %d" % counts.get("ok", 0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
