#!/usr/bin/env python3
"""Generate assets/icons.js - inline SVG for icons chosen at runtime by JS.

Most Font Awesome tags were static and got inlined directly into the HTML.
A few pages pick an icon in JavaScript (which class name to use depends on
state), so those need a helper that can build the same SVG on demand.
"""

import json
import os

from lib_catalog import ROOT
from replace_fontawesome import svg_body

OUT = os.path.join(ROOT, "assets", "icons.js")

# Icons that page JavaScript selects dynamically.
NEEDED = [
    ("cat", "solid"),
    ("dog", "solid"),
    ("dove", "solid"),
    ("layer-group", "solid"),
    ("bars", "solid"),
    ("check", "solid"),
    ("triangle-exclamation", "solid"),
    ("circle-plus", "solid"),
    ("circle-minus", "solid"),
]


def main():
    icons = {}
    for name, style in NEEDED:
        got = svg_body(style, name)
        if got is None:
            raise SystemExit("missing icon: %s" % name)
        icons[name] = {"v": got[0], "d": got[1]}

    js = """/* GENERATED by tools/build_icons_js.py - do not edit.
 * Inline SVG for the icons that page scripts choose at runtime.
 * Usage: vzIcon('check', 'extra-class', 'color:red')
 */
window.VZ_ICONS = %s;
window.vzIcon = function (name, cls, style) {
  var i = window.VZ_ICONS[name];
  if (!i) return '';
  return '<svg class="vz-icon ' + (cls || '') + '" viewBox="' + i.v +
    '" fill="currentColor" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"' +
    (style ? ' style="' + style + '"' : '') + '>' + i.d + '</svg>';
};
""" % json.dumps(icons, separators=(",", ":"))

    open(OUT, "w", encoding="utf-8").write(js)
    print("wrote %s (%d icons, %d bytes)" % (
        os.path.relpath(OUT, ROOT), len(icons), len(js)))


if __name__ == "__main__":
    main()
