#!/usr/bin/env python3
"""Rewrite every page's <head>: local assets in place of CDNs, plus SEO tags.

Idempotent - the generated block is delimited by VIZLEARN:HEAD markers, so a
re-run replaces it rather than stacking duplicates.

  * drops cdn.tailwindcss.com (a ~120 KB in-browser compiler) and the inline
    per-page tailwind.config, for one prebuilt assets/vizlearn.css
  * drops the Font Awesome CSS + webfonts (icons are now inline SVG)
  * adds favicon, canonical, Open Graph, Twitter card and JSON-LD
"""

import glob
import html
import json
import os
import re

from lib_catalog import ROOT, SITE, counts, modules, page_description
from lib_pages import (is_tool_page, tool_page,
                       DIR_TO_TOPIC, STATIC_LD_TYPE, STATIC_PAGES, STATIC_TITLES,
                       TOPICS, first_published, is_static_page, is_topic_page,
                       last_modified, page_url, topic_url)
from static_pages import PAGES as STATIC_COPY

BEGIN = "<!-- VIZLEARN:HEAD:BEGIN (generated by tools/build_seo.py) -->"
END = "<!-- VIZLEARN:HEAD:END -->"

AUTHOR = "Ashish Jangra"
LIGHT_BG = "#f0fdf4"   # --bg-body in light mode, the default theme

# Google AdSense loader. Google expects this in <head> on every page you want
# ads on; it also serves as the site-verification signal during review. It does
# nothing visible until the account is approved.
ADSENSE_CLIENT = "ca-pub-7551664560637561"

# Display-unit slot IDs, filled in from the AdSense dashboard once the units
# exist. An empty string means "this placement is off": tools/build_ads.py
# writes its markers either way, so switching a placement on is this one
# constant plus a rebuild, not another pass over 343 pages.
#
# "top" sits between the visualisation and the written article; "bottom" sits
# below the article and above the footer. Nothing is placed inside a
# visualisation, which is what about.html promises readers.
AD_SLOTS = {
    "top": "",
    "bottom": "",
}
ADSENSE_TAG = (
    '    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'
    '?client=%s" crossorigin="anonymous"></script>' % ADSENSE_CLIENT
)
# Any copy placed by hand outside the generated block, so re-runs cannot stack.
LOOSE_ADSENSE = re.compile(
    r'[ \t]*<script[^>]*pagead2\.googlesyndication\.com[^>]*>\s*</script>\n?', re.S)

# Pages whose description this build owns. index.html is here because its
# description quotes a module count, which cannot be maintained by hand -
# it read "166" for every module added after it was written. Entries listed
# in GENERATED_DESC below are rewritten rather than merely defaulted.
FALLBACK_DESC = {
    # Derived, not transcribed: this string is the hub's search snippet and
    # its social card, and it read "166" for every module added after it was
    # written.
    "index.html": (
        "VizLearn makes AI, Machine Learning, Deep Learning, Algorithms and "
        "Maths intuitive through %d free interactive visualizations. No jargon, "
        "no login, nothing to install." % counts()["modules"]
    ),
    "computer_vision/cnn.html": (
        "Explore a convolutional neural network layer by layer in 3D - see how "
        "filters, feature maps and pooling turn pixels into predictions."
    ),
    "natural_language_processing/rnn.html": (
        "See how a recurrent neural network processes a sequence step by step, "
        "carrying hidden state from one time step to the next."
    ),
}

# Descriptions this build replaces even when the page already has one.
GENERATED_DESC = {"index.html"}

CDN_TAILWIND = re.compile(r'[ \t]*<script src="https://cdn\.tailwindcss\.com"></script>\n?')
CDN_FA = re.compile(r'[ \t]*<link[^>]*font-awesome[^>]*>\n?')
INLINE_TW_CONFIG = re.compile(
    r'[ \t]*<script>\s*tailwind\.config\s*=\s*\{.*?\}\s*</script>\n?', re.S)
# 23 pages wrapped the config in a retry loop that polls for window.tailwind.
# With the CDN gone that would spin on setTimeout forever, so it has to go too.
INIT_TAILWIND = re.compile(
    r'[ \t]*<script>(?:(?!</script>).)*?initTailwind(?:(?!</script>).)*?</script>\n?', re.S)
GENERATED = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)

# Shared runtime, loaded by every page including the hub. Kept here rather than
# per-page so index.html and the modules can never drift apart again.
SCRIPTS_BEGIN = "<!-- VIZLEARN:SCRIPTS:BEGIN -->"
SCRIPTS_END = "<!-- VIZLEARN:SCRIPTS:END -->"
SCRIPTS_BLOCK = re.compile(
    re.escape(SCRIPTS_BEGIN) + r".*?" + re.escape(SCRIPTS_END) + r"\n?", re.S)
# (filename, hook) for every script the build puts at the end of a page.
#
# A hook of None means "always" - the shell, the search index, the theme
# switch, the things every page uses. Anything else is a substring the page's
# own markup must contain before the script is worth sending, taken from the
# selector the script binds to.
#
# The list used to be flat, and every page loaded all of it. That put
# vizlearn-ml.js and vizlearn-cv.js - 78 KB and 58 KB - on all 427 pages, of
# which about forty each actually use them, and a maths article was fetching
# and parsing eleven scripts that could never find anything to bind to.
# Shipping a script to a page that cannot use it is not free just because the
# script exits early: it is still downloaded, parsed and executed.
#
# Every script is deferred. They all bind on DOMContentLoaded already, so
# nothing changes about when they run - but an undeferred <script src> blocks
# the parser while it fetches, and twenty of them in a row is the lag.
SHARED_SCRIPTS = (
    # The 139 KB catalog is NOT listed here. search.js fetches it on the first
    # focus of the search box, so a reader who never searches never pays for
    # it. The one page that needs it synchronously is /saved/, whose own
    # saved.js reads window.VIZLEARN_MODULES at load.
    ("modules.js", "assets/saved.js"),
    ("search.js", None),
    ("vizlearn.js", None),         # theme, nav, the shell
    ("vizlearn-state.js", None),   # progress and bookmarks, on every page
    ("vizlearn-pwa.js", None),
    ("vizlearn-keys.js", None),    # keyboard shortcuts
    ("glossary.js", None),         # term data for the definition cards
    ("vizlearn-glossary.js", None),

    # The quiz and step players read a JSON island the build emits.
    ("vizlearn-lab.js", "vz-lab-data"),
    # The home page rails.
    ("vizlearn-rails.js", "carousel-wrapper"),

    # Runnable editors, one per language.
    ("vizlearn-python.js", "vz-py"),
    # SQLite compiled to wasm. Hooked like the rest rather than injected
    # per page: the hook already means "only pages that have an editor",
    # which was the reason it used to be injected separately, and one
    # mechanism is easier to reason about than two.
    ("vizlearn-sql.js", "data-vz-sql"),
    # /notebook/ keeps its own kernel: cells share a namespace, which the
    # one-shot runner above deliberately does not do.
    ("vizlearn-notebook.js", "vz-nb"),
    ("vizlearn-js.js", "vz-js"),
    ("vizlearn-html.js", "vz-html"),
    # Highlights editor blocks and the static <pre><code class="language-x">
    # blocks prose.py writes into articles. The second hook was missing, which
    # is why article code was never coloured while the editor beside it was.
    ("vizlearn-code.js", ("data-vz-code", 'class="language-')),
    # The labs' resizable split.
    ("vizlearn-ide.js", "data-vz-ide"),

    # The /interview/ step player.
    ("vizlearn-interview.js", "data-vz-iv"),
    # The retrieval widgets on the generated gen_ai/ pages.
    ("vizlearn-ragviz.js", "data-vz-rv"),
    # The image-processing harness on the generated computer_vision/ modules.
    ("vizlearn-cv.js", "data-vz-cv"),
    # Query variants and two-transaction timelines on the database/ modules.
    # This only wires buttons; the SQL engine itself is vizlearn-sql.js above.
    ("vizlearn-dbq.js", "data-vz-dbq"),
    # The plotter and numeric helpers, shared by the two harnesses below.
    # Listed before them: deferred scripts run in document order, so this
    # defines window.VizML before either reads it.
    ("vizlearn-plot.js", ("data-vz-ml", "data-vz-math", "data-vz-dl")),
    # The workflow simulations on the generated machine_learning/ modules.
    ("vizlearn-ml.js", "data-vz-ml"),
    # The demonstrations on the generated maths/ modules.
    ("vizlearn-math.js", "data-vz-math"),
    # The demonstrations on the generated deep_learning/ modules.
    ("vizlearn-dl.js", "data-vz-dl"),
    # Copy buttons. Wanted wherever there is a code block of either kind.
    ("vizlearn-copy.js", ("<pre", "data-vz-code")),
)


def scripts_for(src):
    """The scripts this page can actually use, in load order."""
    out = []
    for name, hook in SHARED_SCRIPTS:
        if hook is None:
            out.append(name)
        elif isinstance(hook, tuple):
            if any(h in src for h in hook):
                out.append(name)
        elif hook in src:
            out.append(name)
    return out


# The one-time migration wrote these directly; drop the loose copies.
LOOSE_SCRIPT = re.compile(
    r'[ \t]*<script src="(?:\.\./)*assets/(?:modules|search|vizlearn|vizlearn-lab|vizlearn-state|vizlearn-pwa|vizlearn-keys|glossary|vizlearn-glossary|vizlearn-python|vizlearn-notebook|vizlearn-rails|vizlearn-js|vizlearn-html|vizlearn-code|vizlearn-interview|vizlearn-ragviz)\.js"></script>\n?')

META_DESC = re.compile(r'<meta\s+name="description"\s+content="([^"]*)"\s*/?>', re.I)
TITLE = re.compile(r"<title>(.*?)</title>", re.S)


def og_image(rel):
    slug = "index" if rel == "index.html" else rel.replace("/", "__").replace(".html", "")
    return SITE + "/assets/og/" + slug + ".png"


def breadcrumbs(rel, short, mod):
    """BreadcrumbList JSON-LD, or None for the hub.

    Every page already showed a visible "Home / ..." trail, but without this
    Google has no way to read it, so results kept rendering the raw URL path
    instead of the trail.
    """
    if rel == "index.html":
        return None

    trail = [("Home", SITE + "/")]

    if is_topic_page(rel):
        key = DIR_TO_TOPIC[rel.split("/")[0]]
        trail.append((TOPICS[key]["title"], topic_url(key)))
    elif is_static_page(rel):
        trail.append((STATIC_TITLES[rel], page_url(rel)))
    elif is_tool_page(rel):
        trail.append((tool_page(rel)["title"], page_url(rel)))
    else:
        # A module sits under its track, which is now a real page.
        key = DIR_TO_TOPIC.get(mod["dir"]) if mod else None
        if key:
            trail.append((TOPICS[key]["title"], topic_url(key)))
        trail.append((short, page_url(rel)))

    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": name, "item": url}
            for i, (name, url) in enumerate(trail)
        ],
    }


def build_block(rel, title, desc, prefix, mod, needs_icons=False):
    """The generated <head> block for one page."""
    url = page_url(rel)
    img = og_image(rel)
    short = title.replace("VizLearn - ", "").split(" | ")[0].strip() or "VizLearn"
    modified = last_modified(rel)
    published = first_published(rel)
    e = html.escape

    if is_topic_page(rel):
        key = DIR_TO_TOPIC[rel.split("/")[0]]
        t = TOPICS[key]
        topic_mods = [m for m in modules() if m["dir"] == t["dir"]]
        ld = {
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            "name": t["h1"],
            "headline": t["h1"],
            "description": desc,
            "url": url,
            "image": img,
            "inLanguage": "en",
            "isPartOf": {"@type": "WebSite", "name": "VizLearn", "url": SITE + "/"},
            "dateModified": modified,
            "about": t["title"],
            "publisher": {"@type": "Organization", "name": "VizLearn", "url": SITE + "/",
                          "logo": SITE + "/assets/icon-512.png"},
            "mainEntity": {
                "@type": "ItemList",
                "name": "%s modules" % t["title"],
                "numberOfItems": len(topic_mods),
                "itemListOrder": "https://schema.org/ItemListOrderAscending",
                "itemListElement": [
                    {"@type": "ListItem", "position": m["index"] + 1,
                     "name": m["title"], "url": SITE + "/" + m["path"]}
                    for m in topic_mods
                ],
            },
        }
    elif is_static_page(rel):
        ld = {
            "@context": "https://schema.org",
            "@type": STATIC_LD_TYPE[rel],
            "name": STATIC_TITLES[rel],
            "headline": STATIC_TITLES[rel],
            "description": desc,
            "url": url,
            "inLanguage": "en",
            "datePublished": published,
            "dateModified": modified,
            "isPartOf": {"@type": "WebSite", "name": "VizLearn", "url": SITE + "/"},
            "publisher": {"@type": "Organization", "name": "VizLearn", "url": SITE + "/",
                          "logo": SITE + "/assets/icon-512.png"},
        }
    elif rel == "index.html":
        ld = {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": "VizLearn",
            "url": SITE + "/",
            "description": desc,
            "inLanguage": "en",
            "publisher": {"@type": "Organization", "name": "VizLearn", "url": SITE + "/",
                          "logo": SITE + "/assets/icon-512.png"},
            "potentialAction": {
                "@type": "SearchAction",
                "target": {"@type": "EntryPoint",
                           "urlTemplate": SITE + "/?q={search_term_string}"},
                "query-input": "required name=search_term_string",
            },
        }
    else:
        ld = {
            "@context": "https://schema.org",
            "@type": "LearningResource",
            "name": short,
            "headline": short,
            "description": desc,
            "url": url,
            "image": img,
            "inLanguage": "en",
            "isAccessibleForFree": True,
            "learningResourceType": "Interactive visualization",
            "educationalLevel": "Beginner",
            "typicalAgeRange": "16-",
            "datePublished": published,
            "dateModified": modified,
            "author": {"@type": "Person", "name": AUTHOR},
            "publisher": {"@type": "Organization", "name": "VizLearn", "url": SITE + "/",
                          "logo": SITE + "/assets/icon-512.png"},
            "isPartOf": {"@type": "WebSite", "name": "VizLearn", "url": SITE + "/"},
        }
        if mod:
            ld["about"] = mod["category"]

    lines = [
        BEGIN,
        '    <link rel="canonical" href="%s">' % url,
    ] + ([
        '    <meta name="robots" content="noindex, follow">',
    ] if rel in NOINDEX else []) + [
        "",
        "    <!-- icons -->",
        '    <link rel="icon" type="image/svg+xml" href="%sassets/favicon.svg">' % prefix,
        '    <link rel="icon" type="image/x-icon" href="%sfavicon.ico">' % prefix,
        '    <link rel="apple-touch-icon" href="%sassets/apple-touch-icon.png">' % prefix,
        # Follows the default theme: light ships as the default, so the
        # browser chrome should not be painted dark around a light page.
        '    <meta name="theme-color" content="%s">' % LIGHT_BG,
        "",
        "    <!-- installable -->",
        '    <link rel="manifest" href="%smanifest.webmanifest">' % prefix,
        '    <meta name="apple-mobile-web-app-capable" content="yes">',
        '    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">',
        '    <meta name="apple-mobile-web-app-title" content="VizLearn">',
        "",
        "    <!-- social preview -->",
        '    <meta property="og:type" content="%s">' % og_type(rel),
        '    <meta property="og:site_name" content="VizLearn">',
        '    <meta property="og:title" content="%s">' % e(short if rel != "index.html" else "VizLearn - Interactive AI & Algorithm Visualizations"),
        '    <meta property="og:description" content="%s">' % e(desc),
        '    <meta property="og:url" content="%s">' % url,
        '    <meta property="og:image" content="%s">' % img,
        '    <meta property="og:image:width" content="1200">',
        '    <meta property="og:image:height" content="630">',
        '    <meta property="og:image:alt" content="%s">' % e(og_alt(rel, short)),
        '    <meta property="og:locale" content="en_US">',
    ] + ([
        '    <meta property="article:modified_time" content="%s">' % modified,
        '    <meta property="article:published_time" content="%s">' % published,
    ] if og_type(rel) == "article" else []) + [
        '    <meta name="twitter:card" content="summary_large_image">',
        '    <meta name="twitter:title" content="%s">' % e(short),
        '    <meta name="twitter:description" content="%s">' % e(desc),
        '    <meta name="twitter:image" content="%s">' % img,
        "",
        "    <!-- prebuilt stylesheet (replaces the Tailwind CDN compiler) -->",
        '    <link rel="stylesheet" href="%sassets/vizlearn.css">' % prefix,
        "",
        "    <!-- Google AdSense -->",
        ADSENSE_TAG,
    ] + ([
        "",
        "    <!-- runtime icon lookup, for icons this page picks in JS -->",
        '    <script defer src="%sassets/icons.js"></script>' % prefix,
    ] if needs_icons else []) + [
        "",
        '    <meta name="author" content="%s">' % e(AUTHOR),
        '    <meta name="last-modified" content="%s">' % modified,
    ] + ([
        '    <meta name="keywords" content="%s">'
        % e(TOPICS[DIR_TO_TOPIC[rel.split("/")[0]]]["keywords"]),
    ] if is_topic_page(rel) else []) + [
        "",
        '    <script type="application/ld+json">',
        json.dumps(ld, indent=2, ensure_ascii=False),
        "    </script>",
    ]

    crumbs = breadcrumbs(rel, short, mod)
    if crumbs:
        lines += [
            '    <script type="application/ld+json">',
            json.dumps(crumbs, indent=2, ensure_ascii=False),
            "    </script>",
        ]

    lines.append(END)
    return "\n".join(lines) + "\n"


def og_type(rel):
    if rel == "index.html" or is_topic_page(rel) or is_tool_page(rel):
        return "website"
    if is_static_page(rel):
        return "website"
    return "article"


def og_alt(rel, short):
    if is_tool_page(rel):
        return "%s on VizLearn" % tool_page(rel)["title"]
    if is_topic_page(rel):
        return "%s track on VizLearn" % short
    if is_static_page(rel):
        return "%s - VizLearn" % short
    return "%s - interactive visualization on VizLearn" % short


def generated_description(rel, mods):
    """Descriptions for the pages this build generates.

    Module descriptions come from descriptions.py or the page's own <meta>;
    topic and static pages have no author to read one from, so they get theirs
    from the same copy the page body is rendered from.
    """
    if is_topic_page(rel):
        key = DIR_TO_TOPIC[rel.split("/")[0]]
        t = TOPICS[key]
        n = len([m for m in mods if m["dir"] == t["dir"]])
        return "%s %d free interactive modules, in teaching order - no login, no setup." % (
            t["lead"], n)
    if is_static_page(rel):
        return STATIC_COPY[rel]["description"]
    if is_tool_page(rel):
        return tool_page(rel)["description"]
    return None


# App pages, not articles. /saved/ is a bookmarks list, /map/ a navigation
# graph and /practice/ a spaced-repetition queue - each is a few dozen words
# of prose wrapped around state that only exists in the reader's own browser,
# so there is nothing on them for a crawler to index. /glossary/ and
# /whats-new/ are excluded from this list because they are real content: the
# first defines every term the modules assume, the second is a written record
# of what shipped and when.
NOINDEX = {
    "saved/index.html",
    "map/index.html",
    "practice/index.html",
}


def main():
    mods = modules()
    by_path = {m["path"]: m for m in mods}
    files = sorted(glob.glob(os.path.join(ROOT, "*", "*.html")))
    files = [f for f in files
             if os.path.basename(os.path.dirname(f)) not in ("tools", "assets", "node_modules")]
    files.append(os.path.join(ROOT, "index.html"))
    files += [os.path.join(ROOT, p) for p in STATIC_PAGES
              if os.path.exists(os.path.join(ROOT, p))]

    added_desc = 0
    rewritten_desc = 0
    for f in files:
        rel = os.path.relpath(f, ROOT)
        prefix = "../" * rel.count("/")
        src = open(f, encoding="utf-8").read()

        # strip anything we are replacing
        src = GENERATED.sub("", src)
        src = LOOSE_ADSENSE.sub("", src)
        src = CDN_TAILWIND.sub("", src)
        src = CDN_FA.sub("", src)
        src = INLINE_TW_CONFIG.sub("", src)
        src = INIT_TAILWIND.sub("", src)

        tm = TITLE.search(src)
        # Unescaped on the way in because everything downstream escapes again.
        # Without this a title containing "&" ships as "&amp;amp;" in the
        # social cards - it was doing exactly that on five pages ("Algorithms
        # &amp; Data Structures", "Optimizers &amp; the 3D Loss Landscape" and
        # friends), which is what a reader saw in the link preview. `title` is
        # only ever read here for the meta block, never written back into
        # <title>, so decoding it cannot corrupt the page's own heading.
        title = html.unescape(tm.group(1).strip()) if tm else "VizLearn"

        dm = META_DESC.search(src)
        override = generated_description(rel, mods)
        if override is None and rel != "index.html":
            override = page_description(rel)
        if override and (not dm or dm.group(1).strip() != override):
            # Hand-written description wins; write it back into the page so the
            # HTML, the search catalog and the social cards all agree.
            tag = '<meta name="description" content="%s">' % html.escape(override)
            if dm:
                src = src[: dm.start()] + tag + src[dm.end():]
            else:
                anchor = src.index("</title>") + len("</title>\n")
                src = src[:anchor] + "    " + tag + "\n" + src[anchor:]
            desc = override
            rewritten_desc += 1
        elif rel in GENERATED_DESC:
            # Owned by the build: replace whatever the page currently says.
            desc = FALLBACK_DESC[rel]
            tag = '<meta name="description" content="%s">' % html.escape(desc)
            if dm:
                src = src[:dm.start()] + tag + src[dm.end():]
            else:
                anchor = src.index("</title>") + len("</title>\n")
                src = src[:anchor] + "    " + tag + "\n" + src[anchor:]
            rewritten_desc += 1
        elif dm:
            # Same reason as the title above: read out of an escaped attribute,
            # re-escaped by e() when it goes into og:/twitter:description.
            desc = html.unescape(dm.group(1).strip())
        else:
            desc = FALLBACK_DESC.get(rel)
            if not desc:
                short = title.replace("VizLearn - ", "")
                desc = ("Learn %s with a beginner-friendly interactive "
                        "visualization on VizLearn." % short)
            tag = '    <meta name="description" content="%s">\n' % html.escape(desc)
            anchor = src.index("</title>") + len("</title>\n")
            src = src[:anchor] + tag + src[anchor:]
            added_desc += 1

        block = build_block(rel, title, desc, prefix, by_path.get(rel),
                            needs_icons="vzIcon(" in src)

        # Insert just before the page's own <style>, so page rules still win.
        i = src.find("<style>")
        if i == -1:
            i = src.index("</head>")
        # back up to the start of that line
        i = src.rfind("\n", 0, i) + 1
        src = src[:i] + block + src[i:]

        # Scripts, just before </body>. Deferred, and only the ones this
        # page has the markup to use.
        src = SCRIPTS_BLOCK.sub("", src)
        src = LOOSE_SCRIPT.sub("", src)
        tags = SCRIPTS_BEGIN + "\n" + "".join(
            '    <script defer src="%sassets/%s"></script>\n' % (prefix, name)
            for name in scripts_for(src)
        ) + SCRIPTS_END + "\n"
        b = src.rindex("</body>")
        src = src[:b] + tags + src[b:]

        open(f, "w", encoding="utf-8").write(src)

    print("pages updated        : %d" % len(files))
    print("descriptions added   : %d" % added_desc)
    print("descriptions rewritten from descriptions.py : %d" % rewritten_desc)


if __name__ == "__main__":
    main()
