#!/usr/bin/env python3
"""Rewrite every page's <head>: local assets in place of CDNs, plus SEO tags.

Idempotent - the generated block is delimited by VIZLEARN:HEAD markers, so a
re-run replaces it rather than stacking duplicates.

  * drops cdn.tailwindcss.com (a ~120 KB in-browser compiler) and the inline
    per-page tailwind.config, for one prebuilt assets/vizlearn.css
  * drops the Font Awesome CSS + webfonts (icons are now inline SVG)
  * adds favicon, canonical, Open Graph, Twitter card and JSON-LD
"""

import glob
import html
import json
import os
import re

from lib_catalog import ROOT, SITE, modules, page_description

BEGIN = "<!-- VIZLEARN:HEAD:BEGIN (generated by tools/build_seo.py) -->"
END = "<!-- VIZLEARN:HEAD:END -->"

AUTHOR = "Ashish Jangra"

# Pages that had no description of their own.
FALLBACK_DESC = {
    "index.html": (
        "VizLearn makes AI, Machine Learning, Deep Learning, Algorithms and "
        "Maths intuitive through 166 free interactive visualizations. No jargon, "
        "no ads, no login."
    ),
    "computer_vision/cnn.html": (
        "Explore a convolutional neural network layer by layer in 3D - see how "
        "filters, feature maps and pooling turn pixels into predictions."
    ),
    "natural_language_processing/rnn.html": (
        "See how a recurrent neural network processes a sequence step by step, "
        "carrying hidden state from one time step to the next."
    ),
}

CDN_TAILWIND = re.compile(r'[ \t]*<script src="https://cdn\.tailwindcss\.com"></script>\n?')
CDN_FA = re.compile(r'[ \t]*<link[^>]*font-awesome[^>]*>\n?')
INLINE_TW_CONFIG = re.compile(
    r'[ \t]*<script>\s*tailwind\.config\s*=\s*\{.*?\}\s*</script>\n?', re.S)
# 23 pages wrapped the config in a retry loop that polls for window.tailwind.
# With the CDN gone that would spin on setTimeout forever, so it has to go too.
INIT_TAILWIND = re.compile(
    r'[ \t]*<script>(?:(?!</script>).)*?initTailwind(?:(?!</script>).)*?</script>\n?', re.S)
GENERATED = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)

# Shared runtime, loaded by every page including the hub. Kept here rather than
# per-page so index.html and the modules can never drift apart again.
SCRIPTS_BEGIN = "<!-- VIZLEARN:SCRIPTS:BEGIN -->"
SCRIPTS_END = "<!-- VIZLEARN:SCRIPTS:END -->"
SCRIPTS_BLOCK = re.compile(
    re.escape(SCRIPTS_BEGIN) + r".*?" + re.escape(SCRIPTS_END) + r"\n?", re.S)
SHARED_SCRIPTS = ("modules.js", "search.js", "vizlearn.js")
# The one-time migration wrote these directly; drop the loose copies.
LOOSE_SCRIPT = re.compile(
    r'[ \t]*<script src="(?:\.\./)*assets/(?:modules|search|vizlearn)\.js"></script>\n?')

META_DESC = re.compile(r'<meta\s+name="description"\s+content="([^"]*)"\s*/?>', re.I)
TITLE = re.compile(r"<title>(.*?)</title>", re.S)


def page_url(rel):
    return SITE + "/" + ("" if rel == "index.html" else rel)


def og_image(rel):
    slug = "index" if rel == "index.html" else rel.replace("/", "__").replace(".html", "")
    return SITE + "/assets/og/" + slug + ".png"


def build_block(rel, title, desc, prefix, mod, needs_icons=False):
    """The generated <head> block for one page."""
    url = page_url(rel)
    img = og_image(rel)
    short = title.replace("VizLearn - ", "").strip() or "VizLearn"
    e = html.escape

    if rel == "index.html":
        ld = {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": "VizLearn",
            "url": SITE + "/",
            "description": desc,
            "inLanguage": "en",
            "publisher": {"@type": "Organization", "name": "VizLearn", "url": SITE + "/",
                          "logo": SITE + "/assets/icon-512.png"},
            "potentialAction": {
                "@type": "SearchAction",
                "target": {"@type": "EntryPoint",
                           "urlTemplate": SITE + "/?q={search_term_string}"},
                "query-input": "required name=search_term_string",
            },
        }
    else:
        ld = {
            "@context": "https://schema.org",
            "@type": "LearningResource",
            "name": short,
            "headline": short,
            "description": desc,
            "url": url,
            "image": img,
            "inLanguage": "en",
            "isAccessibleForFree": True,
            "learningResourceType": "Interactive visualization",
            "educationalLevel": "Beginner",
            "typicalAgeRange": "16-",
            "author": {"@type": "Person", "name": AUTHOR},
            "publisher": {"@type": "Organization", "name": "VizLearn", "url": SITE + "/",
                          "logo": SITE + "/assets/icon-512.png"},
            "isPartOf": {"@type": "WebSite", "name": "VizLearn", "url": SITE + "/"},
        }
        if mod:
            ld["about"] = mod["category"]

    lines = [
        BEGIN,
        '    <link rel="canonical" href="%s">' % url,
        "",
        "    <!-- icons -->",
        '    <link rel="icon" type="image/svg+xml" href="%sassets/favicon.svg">' % prefix,
        '    <link rel="icon" type="image/x-icon" href="%sfavicon.ico">' % prefix,
        '    <link rel="apple-touch-icon" href="%sassets/apple-touch-icon.png">' % prefix,
        '    <meta name="theme-color" content="#050505">',
        "",
        "    <!-- social preview -->",
        '    <meta property="og:type" content="%s">' % ("website" if rel == "index.html" else "article"),
        '    <meta property="og:site_name" content="VizLearn">',
        '    <meta property="og:title" content="%s">' % e(short if rel != "index.html" else "VizLearn - Interactive AI & Algorithm Visualizations"),
        '    <meta property="og:description" content="%s">' % e(desc),
        '    <meta property="og:url" content="%s">' % url,
        '    <meta property="og:image" content="%s">' % img,
        '    <meta property="og:image:width" content="1200">',
        '    <meta property="og:image:height" content="630">',
        '    <meta property="og:image:alt" content="%s">' % e(short + " - interactive visualization on VizLearn"),
        '    <meta property="og:locale" content="en_US">',
        '    <meta name="twitter:card" content="summary_large_image">',
        '    <meta name="twitter:title" content="%s">' % e(short),
        '    <meta name="twitter:description" content="%s">' % e(desc),
        '    <meta name="twitter:image" content="%s">' % img,
        "",
        "    <!-- prebuilt stylesheet (replaces the Tailwind CDN compiler) -->",
        '    <link rel="stylesheet" href="%sassets/vizlearn.css">' % prefix,
    ] + ([
        "",
        "    <!-- runtime icon lookup, for icons this page picks in JS -->",
        '    <script src="%sassets/icons.js"></script>' % prefix,
    ] if needs_icons else []) + [
        "",
        '    <script type="application/ld+json">',
        json.dumps(ld, indent=2, ensure_ascii=False),
        "    </script>",
        END,
    ]
    return "\n".join(lines) + "\n"


def main():
    by_path = {m["path"]: m for m in modules()}
    files = sorted(glob.glob(os.path.join(ROOT, "*", "*.html")))
    files = [f for f in files
             if os.path.basename(os.path.dirname(f)) not in ("tools", "assets", "node_modules")]
    files.append(os.path.join(ROOT, "index.html"))

    added_desc = 0
    rewritten_desc = 0
    for f in files:
        rel = os.path.relpath(f, ROOT)
        prefix = "../" * rel.count("/")
        src = open(f, encoding="utf-8").read()

        # strip anything we are replacing
        src = GENERATED.sub("", src)
        src = CDN_TAILWIND.sub("", src)
        src = CDN_FA.sub("", src)
        src = INLINE_TW_CONFIG.sub("", src)
        src = INIT_TAILWIND.sub("", src)

        tm = TITLE.search(src)
        title = tm.group(1).strip() if tm else "VizLearn"

        dm = META_DESC.search(src)
        override = page_description(rel) if rel != "index.html" else None
        if override and (not dm or dm.group(1).strip() != override):
            # Hand-written description wins; write it back into the page so the
            # HTML, the search catalog and the social cards all agree.
            tag = '<meta name="description" content="%s">' % html.escape(override)
            if dm:
                src = src[: dm.start()] + tag + src[dm.end():]
            else:
                anchor = src.index("</title>") + len("</title>\n")
                src = src[:anchor] + "    " + tag + "\n" + src[anchor:]
            desc = override
            rewritten_desc += 1
        elif dm:
            desc = dm.group(1).strip()
        else:
            desc = FALLBACK_DESC.get(rel)
            if not desc:
                short = title.replace("VizLearn - ", "")
                desc = ("Learn %s with a beginner-friendly interactive "
                        "visualization on VizLearn." % short)
            tag = '    <meta name="description" content="%s">\n' % html.escape(desc)
            anchor = src.index("</title>") + len("</title>\n")
            src = src[:anchor] + tag + src[anchor:]
            added_desc += 1

        block = build_block(rel, title, desc, prefix, by_path.get(rel),
                            needs_icons="vzIcon(" in src)

        # Insert just before the page's own <style>, so page rules still win.
        i = src.find("<style>")
        if i == -1:
            i = src.index("</head>")
        # back up to the start of that line
        i = src.rfind("\n", 0, i) + 1
        src = src[:i] + block + src[i:]

        # Shared scripts, just before </body>, on every page.
        src = SCRIPTS_BLOCK.sub("", src)
        src = LOOSE_SCRIPT.sub("", src)
        tags = SCRIPTS_BEGIN + "\n" + "".join(
            '    <script src="%sassets/%s"></script>\n' % (prefix, name)
            for name in SHARED_SCRIPTS
        ) + SCRIPTS_END + "\n"
        b = src.rindex("</body>")
        src = src[:b] + tags + src[b:]

        open(f, "w", encoding="utf-8").write(src)

    print("pages updated        : %d" % len(files))
    print("descriptions added   : %d" % added_desc)
    print("descriptions rewritten from descriptions.py : %d" % rewritten_desc)


if __name__ == "__main__":
    main()
