#!/usr/bin/env python3
"""One footer, on every page.

Each page shipped with its own hand-copied footer holding three social icons
and a copyright line. That was fine while the only pages were the hub and the
modules; it is not fine now that the site has a privacy policy that has to be
reachable from everywhere (AdSense requires it, and so does anyone who wants
to know what the cookies are doing).

The replacement adds a track directory and the about/contact/privacy/terms
links, so every page also feeds internal links to the new topic landings.

Idempotent: the output sits between VIZLEARN:FOOTER markers, and the first
run swallows whatever <footer> the page already had.
"""

import glob
import html
import os
import re
import sys

from lib_pages import (GITHUB, KAGGLE, LINKEDIN, STATIC_PAGES, STATIC_TITLES, TOOL_ORDER, TOOL_PAGES,
                       TOPICS, TOPIC_ORDER, is_static_page, is_topic_page)
from lib_catalog import ROOT

BEGIN = "<!-- VIZLEARN:FOOTER:BEGIN (generated by tools/build_footer.py) -->"
END = "<!-- VIZLEARN:FOOTER:END -->"

BLOCK = re.compile(r"[ \t]*" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)
# The hand-written footer, on its first (and only) removal.
LEGACY = re.compile(r"[ \t]*<footer\b.*?</footer>\s*\n?", re.S)

SOCIAL = [
    ("GitHub", GITHUB,
     'M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z',
     "0 0 496 512"),
    ("LinkedIn", LINKEDIN,
     'M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z',
     "0 0 448 512"),
    ("Kaggle", KAGGLE,
     'M304.2 501.5L158.4 320.3 298.2 185c2.6-2.7 1.7-10.5-5.3-10.5h-69.2c-3.5 0-7 1.8-10.5 5.3L80.9 313.5V7.5q0-7.5-7.5-7.5H21.5Q14 0 14 7.5v497q0 7.5 7.5 7.5h51.9q7.5 0 7.5-7.5v-109l30.8-29.3 110.5 140.6c3 3.5 6.5 5.3 10.5 5.3h66.9q5.25 0 6-3z',
     "0 0 320 512"),
]


def social_link(label, href, path, viewbox):
    return (
        '<a href="%s" target="_blank" rel="noopener noreferrer" aria-label="%s" '
        'class="vz-foot-social">'
        '<svg class="vz-icon vz-icon-lg" viewBox="%s" fill="currentColor" aria-hidden="true" '
        'xmlns="http://www.w3.org/2000/svg"><path d="%s"/></svg></a>'
        % (href, label, viewbox, path)
    )


def build(prefix):
    tracks = "".join(
        '<li><a href="%s%s/">%s</a></li>' % (prefix, TOPICS[k]["dir"],
                                             html.escape(TOPICS[k]["title"]))
        for k in TOPIC_ORDER
    )
    # The study tools lead: they are the entries a reader has a reason to open
    # twice, and each was unreachable from anywhere until it appeared here.
    site = "".join(
        '<li><a href="%s%s/">%s</a></li>' % (prefix, TOOL_PAGES[k]["dir"],
                                             html.escape(TOOL_PAGES[k]["title"]))
        for k in TOOL_ORDER if TOOL_PAGES[k].get("footer")
    )
    site += "".join(
        '<li><a href="%s%s">%s</a></li>' % (prefix, p, html.escape(STATIC_TITLES[p]))
        for p in STATIC_PAGES
    )
    socials = "".join(social_link(lbl, href, path, vb) for lbl, href, path, vb in SOCIAL)

    return (
        BEGIN + "\n"
        '    <footer class="vz-footer">\n'
        '        <div class="vz-footer-inner">\n'
        '            <div class="vz-foot-col vz-foot-brand">\n'
        '                <a href="%(p)sindex.html" class="vz-foot-logo">'
        'viz<span>learn</span></a>\n'
        '                <p class="vz-foot-blurb">Interactive visual explainers for AI, '
        'machine learning, algorithms and the maths underneath them.</p>\n'
        '                <div class="vz-foot-socials">%(socials)s</div>\n'
        "            </div>\n"
        '            <nav class="vz-foot-col" aria-label="Tracks">\n'
        '                <h2 class="vz-foot-head">Tracks</h2>\n'
        '                <ul class="vz-foot-list">%(tracks)s</ul>\n'
        "            </nav>\n"
        '            <nav class="vz-foot-col" aria-label="Site">\n'
        '                <h2 class="vz-foot-head">Site</h2>\n'
        '                <ul class="vz-foot-list">%(site)s</ul>\n'
        "            </nav>\n"
        "        </div>\n"
        '        <div class="vz-footer-bar">\n'
        '            <p class="mono-font">&copy; 2026 VizLearn &middot; Built by '
        '<a href="%(gh)s" target="_blank" rel="noopener noreferrer">Ashish Jangra</a></p>\n'
        '            <p class="mono-font vz-foot-note">This site uses cookies for '
        'analytics and advertising &mdash; see the '
        '<a href="%(p)sprivacy.html">Privacy Policy</a>.</p>\n'
        "        </div>\n"
        "    </footer>\n"
        + END + "\n"
    ) % {"p": prefix, "tracks": tracks, "site": site, "socials": socials, "gh": GITHUB}


def routable_files():
    files = sorted(glob.glob(os.path.join(ROOT, "*", "*.html")))
    files = [f for f in files
             if os.path.basename(os.path.dirname(f)) not in ("tools", "assets", "node_modules")]
    files.append(os.path.join(ROOT, "index.html"))
    files += [os.path.join(ROOT, p) for p in STATIC_PAGES
              if os.path.exists(os.path.join(ROOT, p))]
    return files


def main():
    done = legacy_removed = 0
    for f in routable_files():
        rel = os.path.relpath(f, ROOT)
        prefix = "../" * rel.count("/")
        src = open(f, encoding="utf-8").read()

        # Replace in place: whatever we remove, the new footer goes back at the
        # same spot, so the module block (which anchors on "<footer") keeps
        # landing above it rather than below the page's trailing scripts.
        at = None
        m = BLOCK.search(src)
        if m:
            at = m.start()
            src = src[:m.start()] + src[m.end():]
        else:
            m = LEGACY.search(src)
            if m:
                at = m.start()
                src = src[:m.start()] + src[m.end():]
                legacy_removed += 1

        if at is None:
            at = src.rindex("</body>")

        src = src[:at] + build(prefix) + src[at:]

        open(f, "w", encoding="utf-8").write(src)
        done += 1

    print("footers written        : %d" % done)
    print("legacy footers removed : %d" % legacy_removed)
    return 0


if __name__ == "__main__":
    sys.exit(main())
