#!/usr/bin/env python3
"""Replace the placeholder article on the pages listed in articles.py.

Those pages shipped with a generic 9-section skeleton whose sentences repeated
across a dozen other pages. This swaps the body of their
<!-- auto-article-vizlearn --> section for the written content in articles.py,
keeping the surrounding card markup the site already uses.

Idempotent: the replacement is delimited by VIZLEARN:ARTICLE markers.
"""

import os
import re
import sys

from articles import ARTICLES
from lib_catalog import ROOT, modules

BEGIN = "<!-- VIZLEARN:ARTICLE:BEGIN (generated by tools/build_articles.py) -->"
END = "<!-- VIZLEARN:ARTICLE:END -->"
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

# The card that wraps the article body on every page that has one.
SECTION = re.compile(
    r'(<!-- auto-article-vizlearn -->\s*<section\b.*?<div class="card-container[^"]*">\s*)'
    r'(.*?)'
    r'(\s*</div>\s*</section>)',
    re.S,
)


def render(title, entry):
    parts = [
        BEGIN,
        '            <div class="card-header">',
        '                <h2 class="font-bold text-xl md:text-2xl" style="color: var(--text-main)">%s</h2>' % title,
        '                <p class="mt-2 text-sm" style="color: var(--text-muted)">%s</p>'
        % entry["intro"],
        "            </div>",
        '            <div class="p-5 md:p-7 space-y-7 text-sm md:text-base leading-7" style="color: var(--text-main)">',
    ]
    for heading, body in entry["sections"]:
        parts.append("                <div>")
        parts.append(
            '                    <h3 class="text-lg font-bold mb-2" style="color: var(--accent-primary)">%s</h3>'
            % heading
        )
        parts.append("                    %s" % body)
        parts.append("                </div>")
    parts.append("            </div>")
    parts.append(END)
    return "\n".join(parts)


# Pages whose own article is good, but had the generic skeleton bolted on to
# the end of it. Their real sections are numbered "1." while every appended
# filler section is numbered "1)", which makes them safe to strip.
TRIM_APPENDED = [
    "natural_language_processing/word_cloud.html",
    "natural_language_processing/tokenization.html",
    "natural_language_processing/text_normalization_pipeline.html",
]

APPENDED_SECTION = re.compile(
    r'\s*<div(?:\s[^>]*)?>\s*<h3[^>]*>\s*\d\)\s[^<]*</h3>.*?</div>\s*(?=<div|</div>\s*</div>\s*</section>)',
    re.S,
)


def trim_appended(src):
    """Drop the bolted-on 'N)' sections, leaving the page's own article."""
    i = src.find("<!-- auto-article-vizlearn -->")
    if i == -1:
        return src, 0
    j = src.find("VIZLEARN:MODULE:BEGIN", i)
    j = len(src) if j == -1 else j
    body, n = APPENDED_SECTION.subn("\n", src[i:j])
    return src[:i] + body + src[j:], n


def main():
    titles = {m["path"]: m["title"] for m in modules()}
    done = missing = trimmed = 0

    for rel in TRIM_APPENDED:
        path = os.path.join(ROOT, rel)
        src = open(path, encoding="utf-8").read()
        new, n = trim_appended(src)
        if n:
            open(path, "w", encoding="utf-8").write(new)
            trimmed += n
            print("  trimmed %d appended sections from %s" % (n, rel))

    for rel, entry in ARTICLES.items():
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            print("  !! no such page: %s" % rel)
            missing += 1
            continue

        src = open(path, encoding="utf-8").read()
        title = "%s: A Practical Guide" % titles.get(rel, rel)
        block = render(title, entry)

        if BLOCK.search(src):
            src = BLOCK.sub(lambda _: block, src)
        else:
            m = SECTION.search(src)
            if not m:
                print("  !! no auto-article section in %s" % rel)
                missing += 1
                continue
            src = src[: m.start(2)] + "\n" + block + "\n        " + src[m.end(2):]

        open(path, "w", encoding="utf-8").write(src)
        done += 1

    print("articles rewritten : %d" % done)
    if missing:
        print("skipped            : %d" % missing)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
