#!/usr/bin/env python3
"""Inject per-module navigation furniture into all 166 module pages.

Adds, as real markup rather than client-rendered HTML so crawlers follow it:

  * a cheat sheet - the page's own lead paragraph, copy-pasteable
  * a related-modules rail, styled like the hub carousel
  * previous / next links through the module's track
  * a share control in the header

Idempotent: everything lives between VIZLEARN:MODULE / VIZLEARN:SHARE markers
and is replaced on re-run.
"""

import glob
import html
import os
import re
import sys
from html.parser import HTMLParser

from lib_catalog import ROOT, by_topic, modules
from lib_pages import DIR_TO_TOPIC, TOPICS, last_modified, pretty_date

BEGIN = "<!-- VIZLEARN:MODULE:BEGIN (generated by tools/build_module_ui.py) -->"
END = "<!-- VIZLEARN:MODULE:END -->"
SHARE_BEGIN = "<!-- VIZLEARN:SHARE:BEGIN -->"
SHARE_END = "<!-- VIZLEARN:SHARE:END -->"
BYLINE_BEGIN = "<!-- VIZLEARN:BYLINE:BEGIN -->"
BYLINE_END = "<!-- VIZLEARN:BYLINE:END -->"

# The leading whitespace has to be part of the match: the share block is
# injected with its own indentation, so stripping only the markers would leave
# that indentation behind and grow it on every rebuild.
BLOCK = re.compile(r"[ \t]*" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)
SHARE_BLOCK = re.compile(
    r"[ \t]*" + re.escape(SHARE_BEGIN) + r".*?" + re.escape(SHARE_END) + r"\n?", re.S)
BYLINE_BLOCK = re.compile(
    r"[ \t]*" + re.escape(BYLINE_BEGIN) + r".*?" + re.escape(BYLINE_END) + r"\n?", re.S)

RELATED_COUNT = 4

ICON = {
    "left": '<path d="M19 12H5"/><path d="m12 19-7-7 7-7"/>',
    "right": '<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>',
    "note": '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/><path d="M8 13h8M8 17h5"/>',
    "grid": '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
    "copy": '<rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15V5a2 2 0 0 1 2-2h10"/>',
    "share": '<path d="M4 12v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7"/><path d="M16 6l-4-4-4 4"/><path d="M12 2v14"/>',
}


def svg(name, cls="vz-icon"):
    return ('<svg class="%s" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            'stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" '
            'aria-hidden="true">%s</svg>' % (cls, ICON[name]))


# --------------------------------------------------------------------------
# Lead-paragraph extraction
# --------------------------------------------------------------------------

class LeadParagraph(HTMLParser):
    """Collect <p> text, skipping any paragraph that wraps interactive controls.

    Those "paragraphs" are widget panels whose stripped text is a soup of
    button and option labels, which makes a useless summary.
    """

    INTERACTIVE = {"input", "select", "button", "textarea", "canvas", "svg", "table"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.skip = 0
        self.buf = None
        self.dirty = False
        self.paras = []

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style"):
            self.skip += 1
            return
        if self.skip:
            return
        if tag == "p" and self.buf is None:
            self.buf = []
            self.dirty = False
        elif self.buf is not None and tag in self.INTERACTIVE:
            self.dirty = True

    def handle_endtag(self, tag):
        if tag in ("script", "style"):
            self.skip = max(0, self.skip - 1)
            return
        if self.skip:
            return
        if tag == "p" and self.buf is not None:
            text = re.sub(r"\s+", " ", "".join(self.buf)).strip()
            if text and not self.dirty:
                self.paras.append(text)
            self.buf = None

    def handle_data(self, data):
        if self.skip or self.buf is None:
            return
        self.buf.append(data)


# Paragraphs that instruct rather than explain make poor takeaways.
UI_START = re.compile(
    r"^(drag|click|press|tap|slide|move|use the|try |select |toggle|hover|scroll|adjust|watch the|notice)",
    re.I,
)


def lead_paragraph(src, fallback):
    """Best one-paragraph summary of the page, else its meta description."""
    p = LeadParagraph()
    try:
        p.feed(src)
    except Exception:
        return fallback

    good = [t for t in p.paras if 140 <= len(t) <= 650]
    if not good:
        good = [t for t in p.paras if 90 <= len(t) <= 900]
    if not good:
        return fallback

    explanatory = [t for t in good if not UI_START.match(t)]
    pick = (explanatory or good)[0]

    if len(pick) > 520:
        cut = pick.rfind(". ", 0, 520)
        pick = pick[: cut + 1] if cut > 240 else pick[:520].rstrip() + "…"
    return pick


# --------------------------------------------------------------------------
# Markup
# --------------------------------------------------------------------------

def card(mod, root_prefix):
    art = mod["svg"].strip()
    if art.startswith("<svg") and "xmlns=" not in art:
        art = art.replace("<svg", '<svg xmlns="http://www.w3.org/2000/svg"', 1)
    return (
        '<a class="vz-card" href="%s%s" data-vz-path="%s">'
        '<span class="vz-card-art">%s</span>'
        '<span class="vz-card-body">'
        '<span class="vz-card-cat">%s</span>'
        '<span class="vz-card-title">%s</span>'
        "</span></a>"
        % (root_prefix, mod["path"], html.escape(mod["path"]), art,
           html.escape(mod["category"]), html.escape(mod["title"]))
    )


def prevnext(prev, nxt, root_prefix):
    if not prev and not nxt:
        return ""
    out = ['<nav class="vz-prevnext" aria-label="Module navigation">']
    if prev:
        out.append(
            '<a class="vz-pn vz-pn-prev" href="%s%s" rel="prev">%s'
            '<span class="vz-pn-text"><span class="vz-pn-label">Previous</span>'
            '<span class="vz-pn-title">%s</span></span></a>'
            % (root_prefix, prev["path"], svg("left"), html.escape(prev["title"]))
        )
    if nxt:
        out.append(
            '<a class="vz-pn vz-pn-next" href="%s%s" rel="next">'
            '<span class="vz-pn-text"><span class="vz-pn-label">Next</span>'
            '<span class="vz-pn-title">%s</span></span>%s</a>'
            % (root_prefix, nxt["path"], html.escape(nxt["title"]), svg("right"))
        )
    out.append("</nav>")
    return "".join(out)


def build_block(mod, summary, related, prev, nxt, root_prefix):
    cheat = (
        '<section class="vz-cheatsheet" aria-labelledby="vz-cheat-h">'
        '<div class="vz-cheat-top">'
        '<span class="vz-cheat-label">%s Cheat sheet</span>'
        '<button type="button" class="vz-btn" data-vz-copy>%s Copy</button>'
        "</div>"
        '<h2 class="vz-cheat-title" id="vz-cheat-h">%s</h2>'
        '<p class="vz-cheat-text">%s</p>'
        '<div class="vz-cheat-foot">%s &middot; vizlearn.in/%s</div>'
        "</section>"
        % (svg("note"), svg("copy"), html.escape(mod["title"]), html.escape(summary),
           html.escape(mod["category"].upper()), html.escape(mod["path"]))
    )

    rail = (
        '<section class="vz-related" aria-labelledby="vz-rel-h">'
        '<div class="vz-section-head">%s<h2 id="vz-rel-h">More in %s</h2>'
        '<span class="vz-rule"></span></div>'
        '<div class="vz-rail">%s</div>'
        "</section>"
        % (svg("grid"), html.escape(mod["category"]),
           "".join(card(r, root_prefix) for r in related))
    )

    return "%s\n<div class=\"vz-extras\">%s%s%s</div>\n%s\n" % (
        BEGIN, cheat, rail, prevnext(prev, nxt, root_prefix), END
    )


def byline(mod, rel, root_prefix):
    """Track, author and last-updated date, directly under the page title.

    No page carried a date before. Readers of a technical explainer reasonably
    want to know whether they are looking at something maintained, and a
    crawler has nothing to read freshness from without it - the same date goes
    into `dateModified` in the JSON-LD and into the sitemap.
    """
    iso = last_modified(rel)
    key = DIR_TO_TOPIC.get(mod["dir"])
    track = TOPICS[key]["title"] if key else mod["category"]
    href = "%s%s/" % (root_prefix, mod["dir"])

    return (
        BYLINE_BEGIN
        + '<p class="vz-byline">'
          '<a class="vz-byline-track" href="%s">%s</a>'
          '<span class="vz-byline-sep" aria-hidden="true">&middot;</span>'
          '<span>Updated <time datetime="%s">%s</time></span>'
          "</p>"
        % (href, html.escape(track), iso, pretty_date(iso))
        + BYLINE_END
    )


SHARE_MARKUP = (
    SHARE_BEGIN
    + '<div class="vz-share-wrap">'
      '<button type="button" class="vz-share-btn" aria-label="Share this module" '
      'aria-haspopup="true" aria-expanded="false">' + svg("share") + "</button>"
      '<div class="vz-share-menu" role="menu"></div>'
      "</div>"
    + SHARE_END
)


# --------------------------------------------------------------------------

def main():
    mods = modules()
    groups = by_topic()
    by_path = {m["path"]: m for m in mods}

    files = sorted(glob.glob(os.path.join(ROOT, "*", "*.html")))
    files = [f for f in files
             if os.path.basename(os.path.dirname(f)) not in ("tools", "assets", "node_modules")]

    injected = shared = bylines = 0
    fallback_used = 0
    missing_anchor = []

    for f in files:
        rel = os.path.relpath(f, ROOT)
        mod = by_path.get(rel)
        if not mod:
            continue
        root_prefix = "../" * rel.count("/")
        src = open(f, encoding="utf-8").read()

        # Drop previous output first, so the summary is never re-extracted
        # from a cheat sheet we generated on an earlier run.
        src = BLOCK.sub("", src)
        src = SHARE_BLOCK.sub("", src)
        src = BYLINE_BLOCK.sub("", src)

        summary = lead_paragraph(src, mod["desc"])
        if summary == mod["desc"]:
            fallback_used += 1

        # Related: the next few modules in the same track, wrapping around.
        peers = groups[mod["topic"]]
        i = next(k for k, p in enumerate(peers) if p["path"] == rel)
        related = [peers[(i + n) % len(peers)] for n in range(1, RELATED_COUNT + 1)]
        related = [r for r in related if r["path"] != rel][:RELATED_COUNT]

        prev = peers[i - 1] if i > 0 else None
        nxt = peers[i + 1] if i < len(peers) - 1 else None

        block = build_block(mod, summary, related, prev, nxt, root_prefix)

        # Anchor on the footer's *marker*, not on "<footer" itself: the footer
        # is generated between VIZLEARN:FOOTER markers, so anchoring on the
        # element would place this block inside that region - and the next
        # `build_footer` run would then delete this block along with the
        # footer it replaces.
        anchor = src.rfind("<!-- VIZLEARN:FOOTER:BEGIN")
        if anchor == -1:
            anchor = src.rfind("<footer")
        if anchor == -1:
            anchor = src.rindex("</body>")
        anchor = src.rfind("\n", 0, anchor) + 1
        src = src[:anchor] + block + src[anchor:]
        injected += 1

        # Byline, immediately after the page title.
        hm = re.search(r"</h1>", src)
        if hm:
            src = src[:hm.end()] + "\n            " + byline(mod, rel, root_prefix) + \
                src[hm.end():]
            bylines += 1

        # Share control, immediately before the theme toggle in the header.
        tm = src.find('<button id="themeToggle"')
        if tm == -1:
            missing_anchor.append(rel)
        else:
            line = src.rfind("\n", 0, tm) + 1
            src = src[:line] + "                    " + SHARE_MARKUP + "\n" + src[line:]
            shared += 1

        open(f, "w", encoding="utf-8").write(src)

    print("modules updated        : %d" % injected)
    print("bylines added          : %d" % bylines)
    print("share controls added   : %d" % shared)
    print("cheat sheets using the meta description as fallback : %d" % fallback_used)
    if missing_anchor:
        print("\nNO THEME TOGGLE (share control skipped) on %d page(s):" % len(missing_anchor))
        for r in missing_anchor:
            print("  -", r)
    return 0


if __name__ == "__main__":
    sys.exit(main())
