#!/usr/bin/env python3
"""Replace the placeholder article on the pages listed in articles.py.

Those pages shipped with a generic 9-section skeleton whose sentences repeated
across a dozen other pages. This swaps the body of their
<!-- auto-article-vizlearn --> section for the written content in articles.py,
keeping the surrounding card markup the site already uses.

Idempotent: the replacement is delimited by VIZLEARN:ARTICLE markers.
"""

import os
import re
import sys

from articles import ARTICLES
from lib_catalog import ROOT, modules

BEGIN = "<!-- VIZLEARN:ARTICLE:BEGIN (generated by tools/build_articles.py) -->"
END = "<!-- VIZLEARN:ARTICLE:END -->"
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

# --------------------------------------------------------------------------
# Locating the article card
#
# The prose card is wrapped four different ways across the site, depending on
# which generation of the generator built the page: a .card-container, a
# .glass-card, an inline-styled div, and one variant with no marker comment at
# all. Rather than special-case each, walk the tag tree: find the section that
# holds the prose, then replace the inner HTML of the first div inside it.
# --------------------------------------------------------------------------

DIV = re.compile(r"<(/?)div\b[^>]*>", re.I)
SECTION_TAG = re.compile(r"<(/?)section\b[^>]*>", re.I)
MARKER = "<!-- auto-article-vizlearn -->"

# The prose section on pages that carry no marker and no vz-article class.
PROSE_CLASS = re.compile(r'class="[^"]*\bpx-4\b[^"]*max-w-\[1600px\]', re.I)


def _close(src, start, tag_re):
    """Index just past the tag closing the element opened at `start`."""
    depth = 0
    for m in tag_re.finditer(src, start):
        depth += -1 if m.group(1) else 1
        if depth == 0:
            return m.start(), m.end()
    return -1, -1


def article_section(src):
    """(start, end) of the <section> holding the written article."""
    i = src.find(MARKER)
    if i != -1:
        s = src.find("<section", i)
        if s != -1:
            return s, _close(src, s, SECTION_TAG)[1]

    for m in re.finditer(r"<section\b[^>]*>", src, re.I):
        open_tag = m.group(0)
        if "vz-predict" in open_tag or "vz-check" in open_tag:
            continue
        close_start, close_end = _close(src, m.start(), SECTION_TAG)
        if close_start == -1:
            continue
        body = src[m.end():close_start]
        prose = "vz-article" in body and "<h3" in body
        bare = PROSE_CLASS.search(open_tag) and "<h2" in body and "<h3" in body
        if "data-vz-prose" in open_tag or prose or bare:
            return m.start(), close_end
    return None


def card_inner(src):
    """(start, end) of the inner HTML of the card wrapping the article."""
    region = article_section(src)
    if not region:
        return None
    start, end = region
    m = re.search(r"<div\b[^>]*>", src[start:end], re.I)
    if not m:
        return None
    close_start, _ = _close(src, start + m.start(), DIV)
    if close_start == -1:
        return None
    return start + m.end(), close_start


def render(title, entry):
    # A page that came with its own card title keeps it; "<module>: A
    # Practical Guide" is only the fallback for the ones that never had one.
    title = entry.get("title") or title
    parts = [
        BEGIN,
        '            <div class="card-header">',
        '                <h2 class="font-bold text-xl md:text-2xl" style="color: var(--text-main)">%s</h2>' % title,
        '                <p class="mt-2 text-sm" style="color: var(--text-muted)">%s</p>'
        % entry["intro"],
        "            </div>",
        '            <div class="vz-article p-5 md:p-7 space-y-7 text-sm md:text-base leading-7" style="color: var(--text-main)">',
    ]
    for heading, body in entry["sections"]:
        parts.append("                <div>")
        parts.append("                    <h3>%s</h3>" % heading)
        parts.append("                    %s" % body)
        parts.append("                </div>")
    parts.append("            </div>")
    parts.append(END)
    return "\n".join(parts)


# Pages whose own article is good, but had the generic skeleton bolted on to
# the end of it. Their real sections are numbered "1." while every appended
# filler section is numbered "1)", which makes them safe to strip.
TRIM_APPENDED = [
    "natural_language_processing/word_cloud.html",
    "natural_language_processing/tokenization.html",
    "natural_language_processing/text_normalization_pipeline.html",
]

APPENDED_SECTION = re.compile(
    r'\s*<div(?:\s[^>]*)?>\s*<h3[^>]*>\s*\d\)\s[^<]*</h3>.*?</div>\s*(?=<div|</div>\s*</div>\s*</section>)',
    re.S,
)


def trim_appended(src):
    """Drop the bolted-on 'N)' sections, leaving the page's own article."""
    i = src.find("<!-- auto-article-vizlearn -->")
    if i == -1:
        return src, 0
    j = src.find("VIZLEARN:MODULE:BEGIN", i)
    j = len(src) if j == -1 else j
    body, n = APPENDED_SECTION.subn("\n", src[i:j])
    return src[:i] + body + src[j:], n


def main():
    titles = {m["path"]: m["title"] for m in modules()}
    done = missing = trimmed = 0

    for rel in TRIM_APPENDED:
        path = os.path.join(ROOT, rel)
        src = open(path, encoding="utf-8").read()
        new, n = trim_appended(src)
        if n:
            open(path, "w", encoding="utf-8").write(new)
            trimmed += n
            print("  trimmed %d appended sections from %s" % (n, rel))

    for rel, entry in ARTICLES.items():
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            print("  !! no such page: %s" % rel)
            missing += 1
            continue

        src = open(path, encoding="utf-8").read()
        title = "%s: A Practical Guide" % titles.get(rel, rel)
        block = render(title, entry)

        if BLOCK.search(src):
            src = BLOCK.sub(lambda _: block, src)
        else:
            span = card_inner(src)
            if not span:
                print("  !! no auto-article section in %s" % rel)
                missing += 1
                continue
            src = src[: span[0]] + "\n" + block + "\n        " + src[span[1]:]

        open(path, "w", encoding="utf-8").write(src)
        done += 1

    print("articles rewritten : %d" % done)
    if missing:
        print("skipped            : %d" % missing)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
