#!/usr/bin/env python3
"""Turn each module's written experiments into things you can actually run,
and add a prediction and an end-of-module check.

Every page already told you to "set the Neighbors (K) slider to 1" and then
left you to scroll up and do it by hand. This reads those instructions,
resolves them against the page's real controls, and attaches a button that
performs them - so the experiment the article describes is one click away from
the visualisation it describes.

Three blocks come out of it:

  * a `Run this` button on every experiment step that resolved to real control
    values (nothing is added to steps that did not resolve - a button that
    silently does nothing is worse than no button);
  * a predict-then-reveal panel, wired to one of those presets and to a real
    readout on the page, so the reveal is measured rather than scripted;
  * a check: multiple choice where tools/labs.py has questions for the module,
    retrieval flashcards built from the page's own key takeaways otherwise.

Idempotent: output lives between VIZLEARN:LAB markers plus the per-step
buttons, all of which are stripped before a re-run.
"""

import glob
import html
import json
import os
import re
import sys

from lib_catalog import ROOT, modules
from lib_controls import action_buttons, controls, normalise
from labs import LABS

BEGIN = "<!-- VIZLEARN:LAB:BEGIN (generated by tools/build_labs.py) -->"
END = "<!-- VIZLEARN:LAB:END -->"
BLOCK = re.compile(r"[ \t]*" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)
RUN_BTN = re.compile(r'<button class="vz-run"[^>]*>.*?</button>', re.S)

TAG = re.compile(r"<[^>]+>")

ICON = {
    "play": '<path d="m5 3 14 9-14 9V3Z"/>',
    "target": '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/>'
              '<path d="M12 1v3M12 20v3M1 12h3M20 12h3"/>',
    "check": '<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 '
             ' 0 0 1 2-2h11"/>',
}


def svg(name):
    return ('<svg class="vz-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            'stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" '
            'aria-hidden="true">%s</svg>' % ICON[name])


def text_of(fragment):
    fragment = re.sub(r"<svg\b.*?</svg>", " ", fragment, flags=re.S | re.I)
    return re.sub(r"\s+", " ", html.unescape(TAG.sub(" ", fragment))).strip()


# --------------------------------------------------------------------------
# Finding the experiment list
# --------------------------------------------------------------------------

# The article sections that hold step-by-step instructions. There is no single
# house style across 166 hand-written pages: "Interactive Exploration Guide" is
# the most common by a distance, then "Guided Experiments" and its variants,
# then the "Try this above" heading that tools/articles.py emits.
EXP_HEADING = re.compile(
    r"<(h[2-6])\b[^>]*>\s*(?:<[^>]+>\s*)*[^<]*?"
    r"(interactive exploration guide|exploration guide|guided experiment|"
    r"try this above|try it yourself|experiments to try|things to try|"
    r"experiment with the visuali|guided tour|try this|explore the visuali)"
    r"[^<]*</\1>",
    re.I,
)


def top_level_items(src, start):
    """Depth-aware scan of the first <ol>/<ul> after `start`.

    Returns [(open_end, close_start)] for each direct <li> child: the slice
    between them is that item's inner HTML, and close_start is where a button
    has to be inserted to land inside the item.
    """
    m = re.compile(r"<(ol|ul)\b[^>]*>", re.I).search(src, start, start + 4000)
    if not m:
        return []
    list_tag = m.group(1).lower()

    i = m.end()
    depth_list = 1
    depth_li = 0
    items = []
    open_end = None

    token = re.compile(r"</?(ol|ul|li)\b[^>]*>", re.I)
    while i < len(src):
        t = token.search(src, i)
        if not t:
            break
        tag = t.group(1).lower()
        closing = t.group(0).startswith("</")
        i = t.end()

        if tag in ("ol", "ul"):
            if closing:
                depth_list -= 1
                if depth_list == 0:
                    break
            else:
                depth_list += 1
        elif tag == "li":
            if closing:
                depth_li -= 1
                if depth_li == 0 and open_end is not None:
                    items.append((open_end, t.start()))
                    open_end = None
            else:
                if depth_li == 0 and depth_list == 1:
                    open_end = t.end()
                depth_li += 1

    return items


# --------------------------------------------------------------------------
# Reading instructions
# --------------------------------------------------------------------------

MIN_WORDS = {"minimum", "min", "lowest", "smallest"}
MAX_WORDS = {"maximum", "max", "highest", "largest", "its max"}

# Words too generic to safely identify a <select>/radio option by themselves.
STOPWORDS = {
    "all", "none", "the", "and", "or", "on", "off", "yes", "no", "one", "two",
    "set", "run", "data", "value", "type", "mode", "step", "next", "reset",
    "start", "stop", "true", "false", "default", "select", "column", "table",
}


def label_pattern(label):
    """Match a control label in prose, tolerating the quoting the pages use."""
    parts = [re.escape(w) for w in re.split(r"\s+", label.strip()) if w]
    if not parts:
        return None
    return re.compile(r"[\"'`“‘]?\s*" + r"[\s\-_]+".join(parts) +
                      r"\s*[\"'`”’]?", re.I)


def resolve_number(window, ctrl):
    """The value a numeric control should take, from the text after its label."""
    low = window.lower()
    head = low[:70]
    if any(w in head for w in MAX_WORDS) and ctrl.get("max"):
        return ctrl["max"]
    if any(w in head for w in MIN_WORDS) and ctrl.get("min"):
        return ctrl["min"]

    m = re.search(r"(?:to|=|of|at)\s*[\"'`]?(-?\d+(?:\.\d+)?)", low[:90])
    if not m:
        m = re.search(r"^[^.]{0,40}?(-?\d+(?:\.\d+)?)", low)
    if not m:
        return None

    val = m.group(1)
    # Refuse a value the control cannot take; the sentence was about something
    # else and matching it would produce a button that lies.
    try:
        v = float(val)
        if ctrl.get("min") not in (None, "") and v < float(ctrl["min"]):
            return None
        if ctrl.get("max") not in (None, "") and v > float(ctrl["max"]):
            return None
    except (TypeError, ValueError):
        pass
    return val


def resolve_option(window, whole, ctrl):
    """The option a select/radio should take."""
    best = None
    for opt in ctrl.get("options", []):
        for cand in (opt.get("label") or "", opt.get("value") or ""):
            cand = cand.strip()
            if len(cand) < 3 or normalise(cand) in STOPWORDS:
                continue
            # A distinctive option name may appear anywhere in the step; a
            # short one has to be next to the control's own label.
            hay = whole if len(cand) >= 5 else window[:80]
            if re.search(r"(?<![a-z0-9])" + re.escape(cand) + r"(?![a-z0-9])", hay, re.I):
                if best is None or len(cand) > len(best[1]):
                    best = (opt.get("value") or opt.get("label"), cand)
    return best[0] if best else None


BOOL_ON = re.compile(r"\b(enable|turn on|switch on|check|tick|activate|with)\b", re.I)
BOOL_OFF = re.compile(r"\b(disable|turn off|switch off|uncheck|untick|deactivate|without)\b", re.I)


def parse_step(step_html, ctrls):
    """A preset for one experiment step, or None if nothing resolved."""
    text = text_of(step_html)
    if not text:
        return None

    sets = []
    used = set()

    for ctrl in ctrls:
        if ctrl["kind"] == "button" or not ctrl.get("label"):
            continue
        pat = label_pattern(ctrl["label"])
        if not pat:
            continue
        m = pat.search(text)
        if not m:
            continue
        window = text[m.end():m.end() + 120]

        value = None
        if ctrl["kind"] in ("range", "number"):
            value = resolve_number(window, ctrl)
        elif ctrl["kind"] in ("select", "radio"):
            value = resolve_option(window, text, ctrl)
        elif ctrl["kind"] == "checkbox":
            near = text[max(0, m.start() - 40):m.end() + 60]
            if BOOL_OFF.search(near):
                value = False
            elif BOOL_ON.search(near):
                value = True

        if value is None:
            continue
        if ctrl["id"] in used:
            continue
        used.add(ctrl["id"])
        sets.append({"id": ctrl["id"], "kind": ctrl["kind"], "value": value})

    # An option named without its control's label ("Select the RANK() function").
    for ctrl in ctrls:
        if ctrl["kind"] not in ("select", "radio") or ctrl["id"] in used:
            continue
        value = resolve_option("", text, ctrl)
        if value is None:
            continue
        used.add(ctrl["id"])
        sets.append({"id": ctrl["id"], "kind": ctrl["kind"], "value": value})

    clicks = []
    for ctrl in ctrls:
        if ctrl["kind"] != "button" or not ctrl.get("label"):
            continue
        lbl = ctrl["label"].strip()
        if len(lbl) < 3:
            continue
        if re.search(r"\b(click|press|hit|tap|then)\b[^.]{0,40}" + re.escape(lbl), text, re.I):
            clicks.append(ctrl["id"])

    if not sets and not clicks:
        return None
    return {"set": sets, "click": clicks}


MAX_ACTIONS = 8


def key_targets(ctrls, src=""):
    """The one or two sliders the arrow keys should drive.

    Every visualisation on the site is driven by a pointer, and a slider is
    already keyboard-accessible once focused - but the drag surfaces are not,
    and nothing tells a keyboard user which control matters. This picks the
    page's widest-range slider as the primary axis and the next widest as the
    secondary, which is the same heuristic derive_preset uses and is right far
    more often than it is wrong.

    Returns {} when the page has no bounded slider at all, and the runtime
    then leaves the page exactly as it found it.
    """
    ranked = []
    for c in ctrls:
        if c["kind"] != "range":
            continue
        lo_s = c["min"] if c["min"] != "" else "0"
        hi_s = c["max"] if c["max"] != "" else "100"
        try:
            lo, hi = float(lo_s), float(hi_s)
            step = float(c["step"] or 1)
        except ValueError:
            continue
        if hi <= lo or step <= 0:
            continue
        ranked.append(((hi - lo) / step, {
            "id": c["id"], "label": c.get("label") or _fallback_label(c),
            "min": lo, "max": hi, "step": step,
        }))

    ranked.sort(key=lambda r: -r[0])
    out = {}
    if ranked:
        out["primary"] = ranked[0][1]
    if len(ranked) > 1:
        out["secondary"] = ranked[1][1]

    # Half the site has no slider at all - the SQL labs, most of the CNN
    # pages - and a select is just as drivable with an arrow key. Fill any
    # empty slot with the longest option list rather than leaving the
    # visualisation a focus stop that does nothing.
    selects = sorted(
        [c for c in ctrls
         if c["kind"] == "select" and len(c.get("options") or []) > 1],
        key=lambda c: -len(c["options"]))
    for c in selects:
        entry = {"id": c["id"], "label": c.get("label") or _fallback_label(c),
                 "kind": "select", "count": len(c["options"])}
        if "primary" not in out:
            out["primary"] = entry
        elif "secondary" not in out and entry["id"] != out["primary"]["id"]:
            out["secondary"] = entry
        else:
            break

    # A bounded number field is a slider with a different skin - same min/max
    # /step, same meaning for an arrow key - and a checkbox is a two-value
    # axis. Neither was ever offered, which is most of why a quarter of the
    # site had no keyboard route in.
    for c in ctrls:
        if "primary" in out and "secondary" in out:
            break
        if c["kind"] == "number":
            lo, hi = c.get("min", ""), c.get("max", "")
            if lo == "" or hi == "":
                continue
            try:
                lo, hi, step = float(lo), float(hi), float(c["step"] or 1)
            except ValueError:
                continue
            if hi <= lo or step <= 0:
                continue
            entry = {"id": c["id"], "label": c.get("label") or _fallback_label(c),
                     "kind": "number", "min": lo, "max": hi, "step": step}
        elif c["kind"] == "checkbox":
            entry = {"id": c["id"], "label": c.get("label") or _fallback_label(c),
                     "kind": "checkbox"}
        else:
            continue
        if "primary" not in out:
            out["primary"] = entry
        elif entry["id"] != out["primary"]["id"]:
            out["secondary"] = entry

    # Nineteen pages are driven purely by buttons - step through a traversal,
    # pick a split, run an epoch - and have no axis to nudge at all. Those get
    # a selectable action list instead, which is the only honest keyboard
    # equivalent of "click the thing".
    if src:
        acts = action_buttons(src)[:MAX_ACTIONS]
        if acts:
            out["actions"] = acts

    return out


def _fallback_label(ctrl):
    """A name for a control whose markup never gave it one.

    Two pages carry an unlabelled slider and lost their keyboard route over
    it. The id is always there and is always descriptive on this site
    ("thresholdSlider", "k-slider"), so it is a better answer than silence.
    """
    s = re.sub(r"[-_]+", " ", ctrl.get("id") or "").strip()
    s = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", s)
    s = re.sub(r"\b(slider|input|range|select|checkbox|ctrl|control)\b", "", s, flags=re.I)
    s = WS_RE.sub(" ", s).strip()
    return s.capitalize() if s else "Value"


WS_RE = re.compile(r"\s+")


def derive_preset(ctrls):
    """A real experiment built from the controls themselves.

    Roughly two thirds of the pages describe their experiments in prose too
    loose to resolve ("slide sigma wider", "load the Parallel preset"). Rather
    than leave those pages without a prediction, push the widest slider to the
    end of its range - which is a genuine experiment, is guaranteed to be a
    legal value, and needs nothing from the article.
    """
    def one(ctrl, value, title):
        return ({"set": [{"id": ctrl["id"], "kind": ctrl["kind"], "value": value}],
                 "click": []}, title)

    # --- a bounded slider, pushed to the far end ------------------------
    best = None
    for c in ctrls:
        if c["kind"] not in ("range", "number") or not c.get("label"):
            continue
        # HTML's own defaults for a range with no bounds declared.
        lo_s = c["min"] if c["min"] != "" else ("0" if c["kind"] == "range" else "")
        hi_s = c["max"] if c["max"] != "" else ("100" if c["kind"] == "range" else "")
        try:
            lo, hi, cur = float(lo_s), float(hi_s), float(c["value"] or lo_s)
        except (TypeError, ValueError):
            continue
        if hi <= lo:
            continue
        span = hi - lo
        if best is None or span > best[0]:
            best = (span, c, lo, hi, cur, lo_s, hi_s)

    if best:
        _, c, lo, hi, cur, lo_s, hi_s = best
        # Move to whichever end is further away, so something visibly changes.
        to_max = (cur - lo) <= (hi - cur)
        return one(c, hi_s if to_max else lo_s,
                   "set %s to its %s (%s)" % (c["label"], "maximum" if to_max else "minimum",
                                              hi_s if to_max else lo_s))

    # --- an unbounded number box, moved by a meaningful amount ----------
    for c in ctrls:
        if c["kind"] != "number" or not c.get("label"):
            continue
        try:
            cur = float(c["value"])
        except (TypeError, ValueError):
            continue
        target = cur * 2 if cur else 10
        value = str(int(target)) if float(target).is_integer() else str(target)
        return one(c, value, "%s %s to %s" % ("double" if cur else "set",
                                              c["label"], value))

    # --- a selector, switched away from its default --------------------
    for c in ctrls:
        if c["kind"] in ("select", "radio") and len(c.get("options") or []) > 1:
            opt = c["options"][-1]
            if not (opt.get("value") or opt.get("label")):
                continue
            return one(c, opt.get("value") or opt.get("label"),
                       "switch %s to %s" % (c["label"] or "the selector",
                                            opt.get("label") or opt.get("value")))

    # --- failing all that, run the page's own action button ------------
    ACTION = re.compile(
        r"(run|animate|play|start|recognize|calculat|generate|sort|search|"
        r"next|step|train|build|solve|encode|process|go)", re.I)
    RESET = re.compile(r"(reset|clear|undo|back|stop|pause)", re.I)

    for pattern in (ACTION, None):
        for c in ctrls:
            if c["kind"] != "button" or not c.get("label"):
                continue
            if RESET.search(c["label"]):
                continue
            if pattern is None or pattern.search(c["label"]):
                return ({"set": [], "click": [c["id"]]},
                        "press %s" % c["label"])
    return None


def step_title(step_html):
    m = re.search(r"<strong\b[^>]*>(.*?)</strong>", step_html, re.S | re.I)
    label = text_of(m.group(1)) if m else text_of(step_html)
    label = label.rstrip(":. ").strip()
    if len(label) > 80:
        label = label[:77].rstrip() + "..."
    return label or "this experiment"


# --------------------------------------------------------------------------
# Readouts
# --------------------------------------------------------------------------

# A readout is a leaf element - one whose content is text, not more markup.
# Matching only leaves is what keeps this from picking up whole panels.
READ_TAG = re.compile(
    r'<(span|div|p|strong|b|td|h[2-6])\b[^>]*\bid="([^"]+)"[^>]*>([^<]*)</\1>', re.I)

# Site furniture rather than anything the visualisation computes.
NOT_READOUT = re.compile(r"^(vz-|search|theme|nav|header|footer|menu|tooltip)", re.I)

# Ranking only - an id matching none of these is still a candidate, because
# plenty of pages name their outputs things like "stHit".
#
# The split matters. A derived metric makes a question worth asking ("what
# happens to accuracy when you double the true positives?"); a raw tally
# usually answers itself ("what happens to the total?"). Both are real
# readouts, so both are offered - the interesting one just goes first.
READOUT_DERIVED = re.compile(
    r"(accur|precis|recall|f1|score|loss|error|entrop|gini|margin|cost|"
    r"rate|prob|mean|avg|ratio|percent|pct|confid|spec|sensit|auc|r2|"
    r"pred|result|output|distance|similar|angle|weight|bias|grad)", re.I)
READOUT_TALLY = re.compile(
    r"(count|total|sum|size|len|num|steps?|swaps?|compar|ops|time|"
    r"hit|miss|node|depth|state|status|badge|display|value|val)", re.I)


def readouts(src, ctrls):
    """Elements on the page that display a computed value.

    Deliberately generous: 166 pages name their outputs 166 different ways
    ("stHit", "valMax", "step-badge", "live-calculation"), so anything that
    looks like a small text leaf with an id is offered as a candidate and the
    runtime picks the first one that is actually showing something.

    Two things are excluded, both for the same reason - they would make the
    prediction trivial rather than interesting:

      * the controls themselves;
      * any element whose starting text is simply a control's current value,
        which is how the pages mirror a slider's position next to its label.
    """
    from lib_controls import _label_before

    control_ids = set(c["id"] for c in ctrls)

    # Most pages mirror a slider's position in a <span> beside its label, named
    # after the same thing: "k-slider" is echoed by "k-value", "lr-slider" by
    # "lr-value". Those are not readouts - asking what happens to Weight w1
    # when you set Weight w1 is not a prediction - so match them by stem.
    #
    # Comparing the displayed text against the control's value is not enough:
    # a slider set to "1" is commonly displayed as "1.0".
    SUFFIX = re.compile(
        r"[-_]?(slider|input|select|range|box|field|btn|button|check|checkbox|"
        r"value|val|display|out|readout|num|txt|text|label)$", re.I)

    def stem(cid):
        prev = None
        while prev != cid:
            prev = cid
            cid = SUFFIX.sub("", cid)
        return cid.lower()

    control_stems = set(stem(c["id"]) for c in ctrls if stem(c["id"]))

    control_values = set()
    for c in ctrls:
        v = c.get("value")
        if v in (None, "", True, False):
            continue
        control_values.add(str(v).strip())
        try:
            # "1" and "1.0" are the same number even though they are not the
            # same string, and the mirror usually formats to a fixed width.
            control_values.add(("%g" % float(v)))
        except (TypeError, ValueError):
            pass

    def from_id(cid):
        """"stepBadge" -> "step badge"."""
        s = re.sub(r"([a-z])([A-Z])", r"\1 \2", cid)
        return s.replace("-", " ").replace("_", " ").strip().lower()

    found = []
    seen = set()
    used_labels = set()

    for m in READ_TAG.finditer(src):
        cid, inner = m.group(2), m.group(3)
        if cid in control_ids or cid in seen or NOT_READOUT.match(cid):
            continue
        if stem(cid) in control_stems:
            continue
        txt = text_of(inner)
        if len(txt) > 24 or txt in control_values:
            continue
        try:
            if ("%g" % float(txt)) in control_values:
                continue
        except (TypeError, ValueError):
            pass
        seen.add(cid)

        label = _label_before(src, m.start())
        # A row of metrics sits close enough together that the scan can pick up
        # the previous one's caption. If a name is already taken, it is the
        # wrong name for this element, so use its id instead.
        if not label or len(label) > 48 or label.lower() in used_labels:
            label = from_id(cid)
        used_labels.add(label.lower())

        # Whether a readout holds a number at *build* time says little: most
        # pages fill theirs in from JavaScript. It is a weak tie-break, not a
        # ranking - assets/vizlearn-lab.js re-checks against the live DOM.
        bucket = 2 if not txt else (0 if re.search(r"\d", txt) else 1)
        found.append({"id": cid, "label": label[:48], "_b": bucket})

    CHROME = re.compile(r"(badge|status|caption|heading|title|legend)", re.I)

    def key(e):
        blob = e["id"] + " " + e["label"]
        # A "badge" is decoration that usually just restates a control.
        if CHROME.search(e["id"]):
            name_rank = 3
        elif READOUT_DERIVED.search(blob):
            name_rank = 0
        elif READOUT_TALLY.search(blob):
            name_rank = 2
        else:
            name_rank = 1
        return (name_rank, e["_b"])

    out = sorted(found, key=key)[:10]
    for e in out:
        del e["_b"]
    return out


# --------------------------------------------------------------------------
# The check
# --------------------------------------------------------------------------

TAKEAWAY_HEAD = re.compile(
    r"<(h[2-6])\b[^>]*>\s*(?:<[^>]+>\s*)*[^<]*?(key takeaway|takeaway|in one line|"
    r"key point|remember|summary)[^<]*</\1>", re.I)

TERM_SPLIT = re.compile(r"^\s*<strong\b[^>]*>(.*?)</strong>\s*[:.—-]*\s*(.*)$", re.S | re.I)


ARTICLE_START = re.compile(r"<!--\s*auto-article-vizlearn\s*-->", re.I)

# Headings that are navigation or instructions rather than an idea to recall.
SKIP_HEADING = re.compile(
    r"(exploration guide|guided experiment|try this|experiment with|more in |"
    r"check yourself|recall check|predict|cheat sheet|on this page|contents)", re.I)

PARA = re.compile(r"<p\b[^>]*>(.*?)</p>", re.S | re.I)


def _trim(body, limit=420):
    body = body.strip()
    if len(body) <= limit:
        return body
    cut = body.rfind(". ", 0, limit)
    return body[:cut + 1] if cut > limit // 2 else body[:limit].rstrip() + "..."


def flashcards(src):
    """Retrieval prompts built from the page's own writing.

    Three sources, in descending order of quality:

      1. a key-takeaway *list* of "<strong>Term:</strong> explanation" items,
         which is already a flashcard in everything but name;
      2. the single key-takeaway paragraph that most pages close on;
      3. the article's own section headings and their opening paragraph.

    Nothing is invented. Every answer shown is text the page already carries,
    which is the whole reason this is safe to generate for 166 pages - a
    machine-written distractor could easily be wrong, but a machine-selected
    quotation cannot.
    """
    cards = []

    # --- 1. a term/definition list --------------------------------------
    m = TAKEAWAY_HEAD.search(src)
    if m:
        for open_end, close_start in top_level_items(src, m.end()):
            tm = TERM_SPLIT.match(src[open_end:close_start].strip())
            if not tm:
                continue
            term = text_of(tm.group(1)).rstrip(":. ").strip()
            body = text_of(tm.group(2)).strip()
            if not term or len(term) > 70 or len(body) < 40:
                continue
            cards.append(("What is meant by “%s” here?" % term, _trim(body)))
        if len(cards) >= 2:
            return cards[:4]

    # --- 2. the one-paragraph takeaway ----------------------------------
    if m and not cards:
        pm = PARA.search(src, m.end(), m.end() + 2500)
        if pm:
            body = text_of(pm.group(1))
            if len(body) >= 60:
                cards.append(("Without scrolling back — what is the one-line "
                              "takeaway from this module?", _trim(body)))

    # --- 3. section headings --------------------------------------------
    am = ARTICLE_START.search(src)
    start = am.end() if am else 0
    stop = src.find("VIZLEARN:LAB:BEGIN")
    stop = len(src) if stop == -1 else stop

    for hm in re.finditer(r"<(h[3-4])\b[^>]*>(.*?)</\1>", src[start:stop], re.S | re.I):
        if len(cards) >= 3:
            break
        heading = text_of(hm.group(2)).strip()
        if not heading or len(heading) > 80 or SKIP_HEADING.search(heading):
            continue
        heading = re.sub(r"^\s*\d+[.)]\s*", "", heading)
        pm = PARA.search(src, start + hm.end(), start + hm.end() + 2000)
        if not pm:
            continue
        body = text_of(pm.group(1))
        if len(body) < 80:
            continue
        prompt = "What does this module say about “%s”?" % heading.rstrip("?:. ")
        if any(prompt == c[0] for c in cards):
            continue
        cards.append((prompt, _trim(body)))

    return cards[:4]


# --------------------------------------------------------------------------
# Markup
# --------------------------------------------------------------------------

def run_button(index, title):
    return ('<button class="vz-run" type="button" data-vz-run="%d" '
            'aria-label="Run this experiment in the visualisation: %s">%s'
            '<span>Run this</span></button>'
            % (index, html.escape(title, quote=True), svg("play")))


def predict_markup(preset_index, title):
    return (
        '<section class="vz-predict" data-vz-preset="%d" aria-labelledby="vz-predict-h">'
        '<div class="vz-section-head">%s<h2 id="vz-predict-h">Predict, then reveal</h2>'
        '<span class="vz-rule"></span></div>'
        '<p class="vz-predict-q">About to run: <strong>%s</strong>. '
        'Before it does &mdash; what happens to '
        '<strong class="vz-predict-readout">the readout</strong>?</p>'
        '<div class="vz-predict-opts">'
        '<button type="button" class="vz-predict-opt" data-vz-guess="up">It goes up</button>'
        '<button type="button" class="vz-predict-opt" data-vz-guess="down">It goes down</button>'
        '<button type="button" class="vz-predict-opt" data-vz-guess="same">It stays the same</button>'
        "</div>"
        '<div class="vz-predict-result" hidden></div>'
        '<p class="vz-predict-hint">Committing to an answer first is the point &mdash; '
        'the reveal runs the experiment on the visualisation above and reads the real '
        'value back, so nothing here is scripted.</p>'
        "</section>"
        % (preset_index, svg("target"), html.escape(title))
    )


def check_markup(questions, cards):
    body = []

    for q in questions:
        opts = "".join(
            '<button type="button" class="vz-q-opt" data-vz-correct="%d">%s</button>'
            % (1 if i == q["answer"] else 0, html.escape(opt))
            for i, opt in enumerate(q["options"])
        )
        why = ('<p class="vz-q-why" hidden>%s</p>' % q["why"]) if q.get("why") else ""
        body.append(
            '<li class="vz-q"><p class="vz-q-text">%s</p>'
            '<div class="vz-q-opts">%s</div>%s</li>'
            % (html.escape(q["q"]), opts, why)
        )

    for prompt, answer in cards:
        body.append(
            '<li class="vz-q vz-q-card"><p class="vz-q-text">%s</p>'
            '<button type="button" class="vz-q-reveal" data-vz-reveal>Show answer</button>'
            '<p class="vz-q-answer" hidden>%s</p></li>'
            % (html.escape(prompt), html.escape(answer))
        )

    kind = "Check yourself" if questions else "Recall check"
    intro = ("Answer without scrolling back up." if questions else
             "Say the answer out loud before you reveal it &mdash; recalling it is "
             "what makes it stick, and rereading it is not.")

    return (
        '<section class="vz-check" aria-labelledby="vz-check-h">'
        '<div class="vz-section-head">%s<h2 id="vz-check-h">%s</h2>'
        '<span class="vz-rule"></span>'
        '<span class="vz-check-score" aria-live="polite">0 of %d</span></div>'
        '<p class="vz-check-intro">%s</p>'
        '<ol class="vz-check-list">%s</ol>'
        "</section>"
        % (svg("check"), kind, len(body), intro, "".join(body))
    )


# --------------------------------------------------------------------------

def viz_container_id(src):
    """The id of the main visualisation element, for scroll-into-view."""
    for pat in (r'<svg\b[^>]*\bid="([^"]+)"', r'<canvas\b[^>]*\bid="([^"]+)"'):
        m = re.search(pat, src, re.I)
        if m:
            return m.group(1)
    return ""


def process(path, rel, authored):
    src = open(path, encoding="utf-8").read()
    src = BLOCK.sub("", src)
    src = RUN_BTN.sub("", src)

    ctrls = controls(src)

    # --- experiments --------------------------------------------------
    presets = []
    inserts = []          # (position, markup) applied right-to-left
    m = EXP_HEADING.search(src)
    if m:
        for open_end, close_start in top_level_items(src, m.end()):
            inner = src[open_end:close_start]
            preset = parse_step(inner, ctrls)
            if not preset:
                continue
            title = step_title(inner)
            presets.append(preset)
            inserts.append((close_start, run_button(len(presets) - 1, title)))
            preset["title"] = title

    for pos, markup in sorted(inserts, reverse=True):
        src = src[:pos] + markup + src[pos:]

    # --- lab block ----------------------------------------------------
    reads = readouts(src, ctrls)
    pieces = []

    # Prefer an experiment that moves a slider: a continuous control gives the
    # readout something to respond to, where a button may just reset the page.
    best = None
    for i, p in enumerate(presets):
        if any(s["kind"] in ("range", "number") for s in p["set"]):
            best = i
            break
    if best is None and presets:
        best = 0

    if best is None:
        # Nothing in the prose resolved; build one from the controls instead.
        derived = derive_preset(ctrls)
        if derived:
            preset, title = derived
            preset["title"] = title
            presets.append(preset)
            best = len(presets) - 1

    if best is not None and reads:
        pieces.append(predict_markup(best, presets[best]["title"]))

    questions = authored.get("check") or []
    cards = [] if questions else flashcards(src)
    if questions or cards:
        pieces.append(check_markup(questions, cards))

    config = {
        "presets": [{"set": p["set"], "click": p["click"]} for p in presets],
        "readouts": reads,
        "viz": viz_container_id(src),
        "keys": key_targets(ctrls, src),
    }

    block = (
        BEGIN + "\n"
        '<div class="vz-lab">%s</div>\n'
        '<script type="application/json" id="vz-lab-data">%s</script>\n'
        % ("".join(pieces), json.dumps(config, ensure_ascii=False))
        + END + "\n"
    )

    # Above the module furniture, and above the footer marker rather than the
    # <footer> element - the footer is generated between markers, so anchoring
    # inside that region would get this block deleted on the next footer run.
    for marker in ("<!-- VIZLEARN:MODULE:BEGIN", "<!-- VIZLEARN:FOOTER:BEGIN", "<footer"):
        anchor = src.rfind(marker)
        if anchor != -1:
            break
    if anchor == -1:
        anchor = src.rindex("</body>")
    anchor = src.rfind("\n", 0, anchor) + 1
    src = src[:anchor] + block + src[anchor:]

    open(path, "w", encoding="utf-8").write(src)
    return {
        "runnable": len(inserts),
        "predict": 1 if (best is not None and reads) else 0,
        "mcq": 1 if questions else 0,
        "cards": 1 if cards else 0,
        "nocheck": 0 if (questions or cards) else 1,
        "rel": rel,
        # Handed back for the practice bank, so the questions on /practice/ and
        # the ones on the module are the same objects rather than a second
        # transcription that could drift.
        "questions": questions,
        "cards_list": cards,
    }


BANK_OUT = os.path.join(ROOT, "assets", "practice-bank.js")

BANK_HEADER = """/* GENERATED FILE - do not edit by hand.
 * Source: the same checks tools/build_labs.py writes into each module.
 * Rebuild: python3 tools/build_labs.py
 */
"""


def write_bank(entries):
    """The question bank /practice/ draws from.

    One record per module that has a check, holding either its authored
    multiple-choice questions or the recall cards derived from its own prose.
    Nothing is invented here that the module page does not already show.
    """
    entries.sort(key=lambda e: (e["cat"], e["title"]))
    with open(BANK_OUT, "w", encoding="utf-8") as fh:
        fh.write(BANK_HEADER)
        fh.write("window.VIZLEARN_PRACTICE = %s;\n"
                 % json.dumps(entries, ensure_ascii=False, indent=1))
    total = sum(len(e["q"]) for e in entries)
    print("practice bank             : %d questions across %d modules"
          % (total, len(entries)))


def main():
    mods = {m["path"] for m in modules()}
    meta = {m["path"]: m for m in modules()}
    bank = []
    files = sorted(glob.glob(os.path.join(ROOT, "*", "*.html")))
    files = [f for f in files
             if os.path.basename(os.path.dirname(f)) not in ("tools", "assets", "node_modules")]

    runnable = pages_runnable = predict = mcq = cards = 0
    no_check = []
    no_predict = []
    pages = 0

    for f in files:
        rel = os.path.relpath(f, ROOT)
        if rel not in mods:
            continue
        pages += 1
        r = process(f, rel, LABS.get(rel, {}))
        runnable += r["runnable"]
        pages_runnable += 1 if r["runnable"] else 0
        predict += r["predict"]
        mcq += r["mcq"]
        cards += r["cards"]
        if r["nocheck"]:
            no_check.append(rel)
        if not r["predict"]:
            no_predict.append(rel)

        qs = [{"t": q["q"], "o": q["options"], "a": q["answer"], "w": q.get("why", "")}
              for q in r["questions"]]
        qs += [{"t": prompt, "ans": answer} for prompt, answer in r["cards_list"]]
        if qs:
            m = meta[rel]
            bank.append({"path": rel, "title": m["title"],
                         "cat": m["category"], "q": qs})

    write_bank(bank)
    print("pages processed           : %d" % pages)
    print("runnable experiments      : %d across %d pages" % (runnable, pages_runnable))
    print("predict-then-reveal       : %d pages" % predict)
    print("checks - authored MCQ     : %d pages" % mcq)
    print("checks - recall cards     : %d pages" % cards)
    if no_check:
        print("\nNO CHECK on %d page(s):" % len(no_check))
        for r in no_check[:20]:
            print("  -", r)
    if no_predict:
        print("\nNO PREDICTION on %d page(s):" % len(no_predict))
        for r in no_predict[:20]:
            print("  -", r)
    return 0


if __name__ == "__main__":
    sys.exit(main())
