#!/usr/bin/env python3
"""Put a real Python interpreter into the dsa/ pages, under the article.

The visualisation shows the algorithm and the article explains it, but until
now the reader never saw the thing they will actually have to write. For
algorithms that gap matters more than anywhere else on the site: the picture of
binary search is obvious, and the off-by-one in `hi = mid - 1` is what people
actually get wrong.

So each covered module gets the same editor /python-lab/ runs - real CPython in
a Web Worker via assets/vizlearn-python.js, already loaded on every page - with
an implementation of *that module's* algorithm in it, printing its own trace as
it goes. Beside it sits a walkthrough keyed to the lines of that program, so
the explanation names the code the reader is looking at rather than pseudocode.

Content lives in tools/code_dsa.py. Nothing here is per-page except that data,
which is the point: one contract, one set of styles, forty implementations.

Insertion point is above the lab block (article, then code, then check), and
the whole thing is delimited by VIZLEARN:CODE markers, so re-running replaces
rather than appends.

Run after tools/build_labs.py - the lab block anchors on the module furniture
below this one, so a labs run temporarily puts its block above ours and this
step puts the order back.

    python3 tools/build_dsa_code.py
"""

import os
import re
import sys

import lib_codelab as codelab
from code_dsa import CODE
from lib_catalog import ROOT

BEGIN = "<!-- VIZLEARN:CODE:BEGIN (generated by tools/build_dsa_code.py) -->"
END = "<!-- VIZLEARN:CODE:END -->"
BLOCK = re.compile(r"[ \t]*" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)

# The anchors, most specific first. The lab block is regenerated on every
# build, so sitting above its marker keeps the reading order stable: run the
# code, then answer the questions about it.
ANCHORS = ("<!-- VIZLEARN:LAB:BEGIN",
           "<!-- VIZLEARN:MODULE:BEGIN",
           "<!-- VIZLEARN:FOOTER:BEGIN",
           "<footer")


def render(entry, prefix):
    return BEGIN + "\n" + codelab.section(entry, prefix, entry["intro"]) + "\n" + END + "\n"


def process(path, rel):
    src = open(path, encoding="utf-8").read()
    src = BLOCK.sub("", src)

    prefix = "../" * rel.count("/")
    block = render(CODE[rel], prefix)

    for marker in ANCHORS:
        anchor = src.rfind(marker)
        if anchor != -1:
            break
    if anchor == -1:
        anchor = src.rindex("</body>")
    anchor = src.rfind("\n", 0, anchor) + 1

    open(path, "w", encoding="utf-8").write(src[:anchor] + block + src[anchor:])


def main():
    done = missing = 0
    for rel in sorted(CODE):
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            print("  !! no such page: %s" % rel)
            missing += 1
            continue
        process(path, rel)
        done += 1

    print("code labs written  : %d" % done)
    if missing:
        print("skipped            : %d" % missing)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
