#!/usr/bin/env python3
"""Inject per-module navigation furniture into all 166 module pages.

Adds, as real markup rather than client-rendered HTML so crawlers follow it:

  * a cheat sheet - the page's own lead paragraph, copy-pasteable
  * a related-modules rail, styled like the hub carousel
  * previous / next links through the module's track
  * a share control in the header

Idempotent: everything lives between VIZLEARN:MODULE / VIZLEARN:SHARE markers
and is replaced on re-run.
"""

import glob
import html
import os
import re
import sys
from html.parser import HTMLParser

from build_seo import AUTHOR
from references import REFERENCES
from lib_catalog import ROOT, by_topic, modules
from lib_pages import (DIR_TO_TOPIC, TOPICS, TRACKS_BEGIN, TRACKS_END,
                       last_modified, pretty_date, tracks_menu)

BEGIN = "<!-- VIZLEARN:MODULE:BEGIN (generated by tools/build_module_ui.py) -->"
END = "<!-- VIZLEARN:MODULE:END -->"
TRACKS_BLOCK = re.compile(
    r"[ \t]*" + re.escape(TRACKS_BEGIN) + r".*?" + re.escape(TRACKS_END) + r"\n?", re.S)

SHARE_BEGIN = "<!-- VIZLEARN:SHARE:BEGIN -->"
SHARE_END = "<!-- VIZLEARN:SHARE:END -->"
SAVE_BEGIN = "<!-- VIZLEARN:SAVE:BEGIN -->"
SAVE_END = "<!-- VIZLEARN:SAVE:END -->"
BYLINE_BEGIN = "<!-- VIZLEARN:BYLINE:BEGIN -->"
BYLINE_END = "<!-- VIZLEARN:BYLINE:END -->"

# The leading whitespace has to be part of the match: the share block is
# injected with its own indentation, so stripping only the markers would leave
# that indentation behind and grow it on every rebuild.
BLOCK = re.compile(r"[ \t]*" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)
SHARE_BLOCK = re.compile(
    r"[ \t]*" + re.escape(SHARE_BEGIN) + r".*?" + re.escape(SHARE_END) + r"\n?", re.S)
BYLINE_BLOCK = re.compile(
    r"[ \t]*" + re.escape(BYLINE_BEGIN) + r".*?" + re.escape(BYLINE_END) + r"\n?", re.S)
SAVE_BLOCK = re.compile(
    r"[ \t]*" + re.escape(SAVE_BEGIN) + r".*?" + re.escape(SAVE_END) + r"\n?", re.S)

RELATED_COUNT = 4

# build_articles.py already delimits the long-form prose section with this.
ARTICLE_MARKER = "<!-- auto-article-vizlearn -->"
PROSE_MAIN = re.compile(r'<main\b[^>]*class="[^"]*\bprose\b[^"]*"[^>]*>')

ICON = {
    "left": '<path d="M19 12H5"/><path d="m12 19-7-7 7-7"/>',
    "right": '<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>',
    "note": '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/><path d="M8 13h8M8 17h5"/>',
    "grid": '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
    "copy": '<rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15V5a2 2 0 0 1 2-2h10"/>',
    "share": '<path d="M4 12v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7"/><path d="M16 6l-4-4-4 4"/><path d="M12 2v14"/>',
    "bookmark": '<path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>',
}


def svg(name, cls="vz-icon"):
    return ('<svg class="%s" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            'stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" '
            'aria-hidden="true">%s</svg>' % (cls, ICON[name]))


# --------------------------------------------------------------------------
# Lead-paragraph extraction
# --------------------------------------------------------------------------

class LeadParagraph(HTMLParser):
    """Collect <p> text, skipping any paragraph that wraps interactive controls.

    Those "paragraphs" are widget panels whose stripped text is a soup of
    button and option labels, which makes a useless summary.
    """

    INTERACTIVE = {"input", "select", "button", "textarea", "canvas", "svg", "table"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.skip = 0
        self.buf = None
        self.dirty = False
        self.paras = []

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style"):
            self.skip += 1
            return
        if self.skip:
            return
        if tag == "p" and self.buf is None:
            self.buf = []
            self.dirty = False
        elif self.buf is not None and tag in self.INTERACTIVE:
            self.dirty = True

    def handle_endtag(self, tag):
        if tag in ("script", "style"):
            self.skip = max(0, self.skip - 1)
            return
        if self.skip:
            return
        if tag == "p" and self.buf is not None:
            text = re.sub(r"\s+", " ", "".join(self.buf)).strip()
            if text and not self.dirty:
                self.paras.append(text)
            self.buf = None

    def handle_data(self, data):
        if self.skip or self.buf is None:
            return
        self.buf.append(data)


# Paragraphs that instruct rather than explain make poor takeaways.
UI_START = re.compile(
    r"^(drag|click|press|tap|slide|move|use the|try |select |toggle|hover|scroll|adjust|watch the|notice)",
    re.I,
)


def lead_paragraph(src, fallback):
    """Best one-paragraph summary of the page, else its meta description."""
    p = LeadParagraph()
    try:
        p.feed(src)
    except Exception:
        return fallback

    good = [t for t in p.paras if 140 <= len(t) <= 650]
    if not good:
        good = [t for t in p.paras if 90 <= len(t) <= 900]
    if not good:
        return fallback

    explanatory = [t for t in good if not UI_START.match(t)]
    pick = (explanatory or good)[0]

    if len(pick) > 520:
        cut = pick.rfind(". ", 0, 520)
        pick = pick[: cut + 1] if cut > 240 else pick[:520].rstrip() + "…"
    return pick


# --------------------------------------------------------------------------
# Markup
# --------------------------------------------------------------------------

def card(mod, root_prefix):
    art = mod["svg"].strip()
    if art.startswith("<svg") and "xmlns=" not in art:
        art = art.replace("<svg", '<svg xmlns="http://www.w3.org/2000/svg"', 1)
    return (
        '<a class="vz-card" href="%s%s" data-vz-path="%s">'
        '<span class="vz-card-art">%s</span>'
        '<span class="vz-card-body">'
        '<span class="vz-card-cat">%s</span>'
        '<span class="vz-card-title">%s</span>'
        "</span></a>"
        % (root_prefix, mod["path"], html.escape(mod["path"]), art,
           html.escape(mod["category"]), html.escape(mod["title"]))
    )


def prevnext(prev, nxt, root_prefix):
    if not prev and not nxt:
        return ""
    out = ['<nav class="vz-prevnext" aria-label="Module navigation">']
    if prev:
        out.append(
            '<a class="vz-pn vz-pn-prev" href="%s%s" rel="prev">%s'
            '<span class="vz-pn-text"><span class="vz-pn-label">Previous</span>'
            '<span class="vz-pn-title">%s</span></span></a>'
            % (root_prefix, prev["path"], svg("left"), html.escape(prev["title"]))
        )
    if nxt:
        out.append(
            '<a class="vz-pn vz-pn-next" href="%s%s" rel="next">'
            '<span class="vz-pn-text"><span class="vz-pn-label">Next</span>'
            '<span class="vz-pn-title">%s</span></span>%s</a>'
            % (root_prefix, nxt["path"], html.escape(nxt["title"]), svg("right"))
        )
    out.append("</nav>")
    return "".join(out)


def build_block(mod, summary, related, prev, nxt, root_prefix, rel):
    cheat = (
        '<section class="vz-cheatsheet" aria-labelledby="vz-cheat-h">'
        '<div class="vz-cheat-top">'
        '<span class="vz-cheat-label">%s Cheat sheet</span>'
        '<button type="button" class="vz-btn" data-vz-copy>%s Copy</button>'
        "</div>"
        '<h2 class="vz-cheat-title" id="vz-cheat-h">%s</h2>'
        '<p class="vz-cheat-text">%s</p>'
        '<div class="vz-cheat-foot">%s &middot; vizlearn.in/%s</div>'
        "</section>"
        % (svg("note"), svg("copy"), html.escape(mod["title"]), html.escape(summary),
           html.escape(mod["category"].upper()), html.escape(mod["path"]))
    )

    rail = (
        '<section class="vz-related" aria-labelledby="vz-rel-h">'
        '<div class="vz-section-head">%s<h2 id="vz-rel-h">More in %s</h2>'
        '<span class="vz-rule"></span></div>'
        '<div class="vz-rail">%s</div>'
        "</section>"
        % (svg("grid"), html.escape(mod["category"]),
           "".join(card(r, root_prefix) for r in related))
    )

    return "%s\n<div class=\"vz-extras\">%s%s%s%s%s</div>\n%s\n" % (
        BEGIN, cheat, rail, further_reading(rel), author_card(root_prefix),
        prevnext(prev, nxt, root_prefix), END
    )


def byline(mod, rel, root_prefix):
    """Track, author and last-updated date, directly under the page title.

    No page carried a date before. Readers of a technical explainer reasonably
    want to know whether they are looking at something maintained, and a
    crawler has nothing to read freshness from without it - the same date goes
    into `dateModified` in the JSON-LD and into the sitemap.
    """
    iso = last_modified(rel)
    key = DIR_TO_TOPIC.get(mod["dir"])
    track = TOPICS[key]["title"] if key else mod["category"]
    href = "%s%s/" % (root_prefix, mod["dir"])

    # The author was named in the docstring, in <meta name="author"> and in the
    # JSON-LD, and nowhere a reader could see it. Who wrote a technical
    # explainer is the first thing anyone assessing it looks for.
    return (
        BYLINE_BEGIN
        + '<p class="vz-byline">'
          '<a class="vz-byline-track" href="%s">%s</a>'
          '<span class="vz-byline-sep" aria-hidden="true">&middot;</span>'
          '<span>By <a class="vz-byline-author" rel="author" href="%sabout.html">%s</a></span>'
          '<span class="vz-byline-sep" aria-hidden="true">&middot;</span>'
          '<span>Updated <time datetime="%s">%s</time></span>'
          "</p>"
        % (href, html.escape(track), root_prefix, html.escape(AUTHOR), iso, pretty_date(iso))
        + BYLINE_END
    )


def further_reading(rel):
    """Primary sources for this module, where there are genuine ones to cite.

    Pages with nothing real to point at get no section - a filler link is
    worse than an absent one.
    """
    refs = REFERENCES.get(rel)
    if not refs:
        return ""
    items = []
    for title, source, url in refs:
        name = html.escape(title)
        if url:
            name = '<a href="%s" rel="noopener nofollow">%s</a>' % (html.escape(url), name)
        items.append('<li><span class="vz-ref-title">%s</span>'
                     '<span class="vz-ref-src">%s</span></li>'
                     % (name, html.escape(source)))
    return (
        '<section class="vz-refs" aria-labelledby="vz-refs-h">'
        '<h2 id="vz-refs-h" class="vz-refs-h">Further reading</h2>'
        '<ul class="vz-ref-list">%s</ul>'
        "</section>" % "".join(items)
    )


def author_card(root_prefix):
    """Short bio under the article.

    A named byline says who; this says on what basis. Both are the visible
    half of what the JSON-LD already claims about authorship.
    """
    return (
        '<section class="vz-author" aria-labelledby="vz-author-h">'
        '<h2 id="vz-author-h" class="vz-author-h">About the author</h2>'
        '<p class="vz-author-body"><strong>%s</strong> builds and maintains VizLearn. '
        'Every module here is written and the visualisation behind it hand-built, '
        'so the numbers in a readout come from the same code that draws the picture. '
        'Corrections are genuinely welcome and get priority over everything else &mdash; '
        'if a page states something wrong, or an animation misrepresents what the '
        'algorithm does, <a href="%scontact.html">get in touch</a>.</p>'
        '<p class="vz-author-links">'
        '<a href="%sabout.html">About VizLearn</a>'
        '<span class="vz-byline-sep" aria-hidden="true">&middot;</span>'
        '<a href="https://github.com/AshishJangra27" rel="noopener me">GitHub</a>'
        '<span class="vz-byline-sep" aria-hidden="true">&middot;</span>'
        '<a href="https://www.linkedin.com/in/ashish-jangra/" rel="noopener me">LinkedIn</a>'
        '<span class="vz-byline-sep" aria-hidden="true">&middot;</span>'
        '<a href="%scontact.html">Contact</a>'
        "</p>"
        "</section>"
        % (html.escape(AUTHOR), root_prefix, root_prefix, root_prefix)
    )


SAVE_MARKUP = (
    SAVE_BEGIN
    + '<div class="vz-save-wrap">'
      '<button type="button" class="vz-save-btn" aria-label="Bookmark this module or add a note" '
      'aria-haspopup="true" aria-expanded="false">' + svg("bookmark") + "</button>"
      '<div class="vz-save-menu" role="dialog" aria-label="Bookmark and note"></div>'
      "</div>"
    + SAVE_END
)


SHARE_MARKUP = (
    SHARE_BEGIN
    + '<div class="vz-share-wrap">'
      '<button type="button" class="vz-share-btn" aria-label="Share this module" '
      'aria-haspopup="true" aria-expanded="false">' + svg("share") + "</button>"
      '<div class="vz-share-menu" role="menu"></div>'
      "</div>"
    + SHARE_END
)


# --------------------------------------------------------------------------

def patch_hub():
    """The hub's header is hand-written and not in modules(), so it is done
    separately. Marker-delimited like everything else, so re-running replaces
    rather than appends."""
    path = os.path.join(ROOT, "index.html")
    src = open(path, encoding="utf-8").read()
    src = TRACKS_BLOCK.sub("", src)

    anchor = src.find('<button id="themeToggle"')
    if anchor == -1:
        return False
    line = src.rfind("\n", 0, anchor) + 1
    src = src[:line] + "                " + tracks_menu("") + "\n" + src[line:]
    open(path, "w", encoding="utf-8").write(src)
    return True


def main():
    mods = modules()
    groups = by_topic()
    by_path = {m["path"]: m for m in mods}

    files = sorted(glob.glob(os.path.join(ROOT, "*", "*.html")))
    files = [f for f in files
             if os.path.basename(os.path.dirname(f)) not in ("tools", "assets", "node_modules")]

    prose_tagged = 0

    injected = shared = bylines = tracked = 0
    fallback_used = 0
    missing_anchor = []

    for f in files:
        rel = os.path.relpath(f, ROOT)
        mod = by_path.get(rel)
        if not mod:
            continue
        root_prefix = "../" * rel.count("/")
        src = open(f, encoding="utf-8").read()

        # Drop previous output first, so the summary is never re-extracted
        # from a cheat sheet we generated on an earlier run.
        src = BLOCK.sub("", src)
        src = SHARE_BLOCK.sub("", src)
        src = SAVE_BLOCK.sub("", src)
        src = BYLINE_BLOCK.sub("", src)
        src = TRACKS_BLOCK.sub("", src)

        summary = lead_paragraph(src, mod["desc"])
        if summary == mod["desc"]:
            fallback_used += 1

        # Related: the next few modules in the same track, wrapping around.
        peers = groups[mod["topic"]]
        i = next(k for k, p in enumerate(peers) if p["path"] == rel)
        related = [peers[(i + n) % len(peers)] for n in range(1, RELATED_COUNT + 1)]
        related = [r for r in related if r["path"] != rel][:RELATED_COUNT]

        prev = peers[i - 1] if i > 0 else None
        nxt = peers[i + 1] if i < len(peers) - 1 else None

        block = build_block(mod, summary, related, prev, nxt, root_prefix, rel)

        # Anchor on the footer's *marker*, not on "<footer" itself: the footer
        # is generated between VIZLEARN:FOOTER markers, so anchoring on the
        # element would place this block inside that region - and the next
        # `build_footer` run would then delete this block along with the
        # footer it replaces.
        anchor = src.rfind("<!-- VIZLEARN:FOOTER:BEGIN")
        if anchor == -1:
            anchor = src.rfind("<footer")
        if anchor == -1:
            anchor = src.rindex("</body>")
        anchor = src.rfind("\n", 0, anchor) + 1
        src = src[:anchor] + block + src[anchor:]
        injected += 1

        # Byline, immediately after the page title.
        hm = re.search(r"</h1>", src)
        if hm:
            src = src[:hm.end()] + "\n            " + byline(mod, rel, root_prefix) + \
                src[hm.end():]
            bylines += 1

        # Tag the long-form prose so the glossary layer can find it.
        #
        # 55 modules use .vz-article, which is both a hook and a set of
        # typography rules. The other 170 predate it and wrap their prose in
        # ad-hoc Tailwind classes, so the glossary silently did nothing on
        # them. Adding .vz-article to those pages would restyle 170 published
        # articles; this adds a styling-free attribute instead, on the section
        # build_articles.py already marks.
        am = src.find(ARTICLE_MARKER)
        if am != -1:
            sm = src.find("<section", am)
            if sm != -1:
                close = src.find(">", sm)
                tag = src[sm:close]
                if "data-vz-prose" not in tag:
                    src = src[:close] + " data-vz-prose" + src[close:]
                    prose_tagged += 1
        elif "data-vz-prose" not in src and 'class="vz-article' not in src:
            # Two pages carry no marker but put their article in a
            # <main class="... prose">, which is Tailwind Typography's own
            # name for exactly this. Only those two match site-wide, and the
            # element holds the article alone - the visualisation is above it.
            pm = PROSE_MAIN.search(src)
            if pm:
                close = pm.end() - 1
                src = src[:close] + " data-vz-prose" + src[close:]
                prose_tagged += 1

        # Share and save controls, immediately before the theme toggle in
        # the header. Save goes in first so that, inserted at the same
        # anchor, the rendered order reads share-then-save.
        tm = src.find('<button id="themeToggle"')
        if tm == -1:
            missing_anchor.append(rel)
        else:
            line = src.rfind("\n", 0, tm) + 1
            src = src[:line] + "                    " + SAVE_MARKUP + "\n" + src[line:]
            line = src.rfind("\n", 0, src.find(SAVE_BEGIN)) + 1
            src = src[:line] + "                    " + SHARE_MARKUP + "\n" + src[line:]
            line = src.rfind("\n", 0, src.find(SHARE_BEGIN)) + 1
            src = src[:line] + "                    " + tracks_menu(root_prefix) + "\n" + src[line:]
            shared += 1
            tracked += 1

        open(f, "w", encoding="utf-8").write(src)

    print("modules updated        : %d" % injected)
    print("prose sections tagged  : %d" % prose_tagged)
    print("bylines added          : %d" % bylines)
    print("share controls added   : %d" % shared)
    print("tracks menus added     : %d%s" % (tracked, " (+ the hub)" if patch_hub() else ""))
    print("cheat sheets using the meta description as fallback : %d" % fallback_used)
    if missing_anchor:
        print("\nNO THEME TOGGLE (share control skipped) on %d page(s):" % len(missing_anchor))
        for r in missing_anchor:
            print("  -", r)
    return 0


if __name__ == "__main__":
    sys.exit(main())
