#!/usr/bin/env python3
"""Restructure index.html: remove the intro band, add the hub sections.

The hub opened with four blocks of prose before it reached a single module,
which is backwards for a site whose argument is that you should go and push a
slider. It now opens on six real modules, then the rails, and keeps the
explanatory material below them.

Everything this writes lives between VIZLEARN:HUB markers and is replaced on
re-run, so it is safe in the build chain. The intro band it removes is
recorded here rather than deleted from history: three cards and a "New here?"
note, one <section class="vz-intro-band">, whose heading existed only to
introduce those cards.

The numbers in the sections come from the catalog, so they cannot drift from
the real module counts.

    python3 tools/build_hub.py
"""

import html
import math
import os
import re
import sys

from lib_catalog import DIR_META, counts, modules

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "index.html")

BEGIN_TOP = "<!-- VIZLEARN:HUB-TOP:BEGIN (generated by tools/build_hub.py) -->"
END_TOP = "<!-- VIZLEARN:HUB-TOP:END -->"
BEGIN_BOT = "<!-- VIZLEARN:HUB-BOTTOM:BEGIN (generated by tools/build_hub.py) -->"
END_BOT = "<!-- VIZLEARN:HUB-BOTTOM:END -->"

TOP_BLOCK = re.compile(re.escape(BEGIN_TOP) + r".*?" + re.escape(END_TOP), re.S)
BOT_BLOCK = re.compile(re.escape(BEGIN_BOT) + r".*?" + re.escape(END_BOT), re.S)
INTRO_BAND = re.compile(r'\s*<section class="vz-intro-band".*?</section>', re.S)

ANCHOR_TOP = '<main id="course-container"'
ANCHOR_BOT = '<footer class="vz-footer"'


def esc(s):
    return html.escape(str(s))


def track_data():
    seen, order = {}, []
    for m in modules():
        d = m["dir"]
        if d not in seen:
            seen[d] = {"dir": d, "label": DIR_META.get(d, (d,))[0], "n": 0,
                       "first": m["path"], "first_title": m["title"]}
            order.append(seen[d])
        seen[d]["n"] += 1
    return sorted(order, key=lambda t: -t["n"])


# --------------------------------------------------------------------------
# Radar
# --------------------------------------------------------------------------
W, H, CX, CY, R = 880, 640, 440, 312, 196


def _pt(i, n, frac):
    a = -math.pi / 2 + (2 * math.pi * i / n)
    return CX + R * frac * math.cos(a), CY + R * frac * math.sin(a)


def radar(tracks):
    n = len(tracks)
    scale = int(math.ceil(tracks[0]["n"] / 10.0) * 10)
    rings = [0.25, 0.5, 0.75, 1.0]
    o = ['<svg class="vzx-radar" viewBox="0 0 %d %d" role="img" '
         'aria-labelledby="vzx-radar-t vzx-radar-d" preserveAspectRatio="xMidYMid meet">' % (W, H),
         '<title id="vzx-radar-t">Modules per track</title>',
         '<desc id="vzx-radar-d">One spoke per track; distance from the centre is '
         "that track's module count. Every spoke is a link, and the same numbers "
         'are in the table beside the chart.</desc>']
    for f in rings:
        o.append('<polygon class="vzx-r-ring" points="%s"/>'
                 % " ".join("%.1f,%.1f" % _pt(i, n, f) for i in range(n)))
    for i in range(n):
        x, y = _pt(i, n, 1.0)
        o.append('<line class="vzx-r-spoke" x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f"/>' % (CX, CY, x, y))
    for f in rings:
        o.append('<text class="vzx-r-scale" x="%.1f" y="%.1f">%d</text>'
                 % (CX + 7, CY - R * f + 4, int(round(scale * f))))
    pts = [_pt(i, n, t["n"] / float(scale)) for i, t in enumerate(tracks)]
    o.append('<polygon class="vzx-r-area" points="%s"/>'
             % " ".join("%.1f,%.1f" % p for p in pts))
    for i, (t, (px, py)) in enumerate(zip(tracks, pts)):
        lx, ly = _pt(i, n, 1.0)
        dx, dy = lx - CX, ly - CY
        d = math.hypot(dx, dy) or 1
        tx, ty = CX + dx / d * (R + 32), CY + dy / d * (R + 32)
        anchor = "middle" if abs(dx) < 14 else ("start" if dx > 0 else "end")
        o.append(
            '<a class="vzx-r-node" href="%s/" data-track="%s" aria-label="%s, %d modules">'
            '<line class="vzx-r-lead" x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f"/>'
            '<circle class="vzx-r-hit" cx="%.1f" cy="%.1f" r="26"/>'
            '<circle class="vzx-r-dot" cx="%.1f" cy="%.1f" r="5"/>'
            '<text class="vzx-r-label" x="%.1f" y="%.1f" text-anchor="%s">%s</text>'
            '<text class="vzx-r-num" x="%.1f" y="%.1f" text-anchor="%s">%d</text></a>'
            % (esc(t["dir"]), esc(t["dir"]), esc(t["label"]), t["n"], CX, CY, px, py,
               px, py, px, py, tx, ty, anchor, esc(t["label"]), tx, ty + 18, anchor, t["n"]))
    o.append("</svg>")
    return "".join(o)


def radar_table(tracks):
    rows = "".join(
        '<tr class="vzx-r-row" data-track="%s"><th scope="row"><a href="%s/">%s</a></th>'
        '<td>%d</td></tr>' % (esc(t["dir"]), esc(t["dir"]), esc(t["label"]), t["n"])
        for t in tracks)
    return ('<table class="vzx-r-table"><caption>Modules per track</caption><thead><tr>'
            '<th scope="col">Track</th><th scope="col">Modules</th></tr></thead>'
            '<tbody>%s</tbody></table>' % rows)


# --------------------------------------------------------------------------
# Sections
# --------------------------------------------------------------------------

def start_here(tracks):
    want = ["python", "maths", "dsa", "machine_learning", "gen_ai", "interview"]
    by = {t["dir"]: t for t in tracks}
    cards = "".join(
        '<a class="vzx-panel vzx-start-card" href="%s"><span class="vzx-start-track">%s</span>'
        '<span class="vzx-start-title">%s</span>'
        '<span class="vzx-start-go">Start the track &rarr;</span></a>'
        % (esc(by[d]["first"]), esc(by[d]["label"]), esc(by[d]["first_title"]))
        for d in want if d in by)
    return ('<section class="vzx-sec" aria-labelledby="vzx-start-h"><div class="vzx-wrap">'
            '<p class="vzx-kicker">Start here</p>'
            '<h2 class="vzx-h" id="vzx-start-h">The first page of six tracks</h2>'
            '<p class="vzx-sub">Each of these is the opening module of its track - the '
            'one that assumes the least.</p><div class="vzx-start">%s</div></div></section>'
            % cards)


def tracks_section(tracks, n_mods, n_tracks):
    return ('<section class="vzx-sec" aria-labelledby="vzx-tracks-h"><div class="vzx-wrap">'
            '<p class="vzx-kicker">Every track</p>'
            '<h2 class="vzx-h" id="vzx-tracks-h">%d modules across %d tracks</h2>'
            '<p class="vzx-sub">Distance from the centre is the number of modules in that '
            'track. Point at a spoke, or tab through them, to pull one out - each is a '
            'link to that track.</p><div class="vzx-radar-wrap"><div class="vzx-radar-col">%s'
            '<p class="vzx-r-readout" role="status" aria-live="polite">Hover a spoke for '
            'its count</p></div>%s</div></div></section>'
            % (n_mods, n_tracks, radar(tracks), radar_table(tracks)))


def how_it_works():
    steps = [
        ("Pick the idea, not the chapter",
         "Every module is one concept with one visualisation. There is no chapter to "
         "finish before it makes sense, and no order you have to arrive in."),
        ("Drive it until it breaks",
         "The controls are the point. Set k to 1 and watch KNN overfit, push the "
         "learning rate until descent diverges. Understanding usually arrives at the "
         "failure, not the happy path."),
        ("Read the code that did it",
         "Where it helps, the same page carries a Python editor running the real thing "
         "in your browser. Change a line, run it, see the output move."),
    ]
    body = "".join(
        '<div class="vzx-step"><span class="vzx-step-n">%d</span><div class="vzx-step-body">'
        '<h3 class="vzx-step-h">%s</h3><p class="vzx-step-p">%s</p></div></div>'
        % (i, esc(t), esc(b)) for i, (t, b) in enumerate(steps, 1))
    return ('<section class="vzx-sec" aria-labelledby="vzx-how-h"><div class="vzx-wrap">'
            '<p class="vzx-kicker">How it works</p>'
            '<h2 class="vzx-h" id="vzx-how-h">Three steps, then you are just using it</h2>'
            '<p class="vzx-sub">No account, no install, nothing gated. Open a page and it '
            'runs.</p><div class="vzx-steps">%s</div></div></section>' % body)


def faq():
    qs = [
        ("Is it actually free?",
         "Yes, and there is nothing to sign up for. No account, no trial, no email wall."),
        ("Does the Python really run?",
         "It runs CPython compiled to WebAssembly, in a worker thread in your browser. "
         "Nothing is uploaded and nothing is executed on a server."),
        ("Does it work offline?",
         "The site installs as an app and caches what you have opened, so pages you have "
         "already visited keep working without a connection."),
        ("Who is it for?",
         "Anyone who has read the definition and still cannot picture the thing. It "
         "assumes no maths degree and leaves nothing as an exercise for the reader."),
    ]
    items = "".join('<div class="vzx-panel vzx-faq-item"><h3 class="vzx-faq-q">%s</h3>'
                    '<p class="vzx-faq-a">%s</p></div>' % (esc(q), esc(a)) for q, a in qs)
    return ('<section class="vzx-sec" aria-labelledby="vzx-faq-h"><div class="vzx-wrap">'
            '<p class="vzx-kicker">Questions</p>'
            '<h2 class="vzx-h" id="vzx-faq-h">The ones worth answering up front</h2>'
            '<div class="vzx-faq">%s</div></div></section>' % items)


def cta(n_mods):
    return ('<section class="vzx-sec vzx-sec-cta"><div class="vzx-wrap"><div class="vzx-cta">'
            '<h2 class="vzx-h" style="margin-top:0">Open one and push a slider</h2>'
            '<p class="vzx-sub" style="margin:0 auto">That is the whole pitch. %d modules, '
            'all of them running the real computation, none of them asking you for '
            'anything first.</p><div class="vzx-cta-row">'
            '<a class="vzx-btn vzx-btn-solid" href="dsa/big_o_notation.html">Start with Big-O</a>'
            '<a class="vzx-btn vzx-btn-ghost" href="map/">Browse the concept map</a>'
            '</div></div></div></section>' % n_mods)


RADAR_JS = """<script>
(function () {
  var wrap = document.querySelector('.vzx-radar-wrap');
  if (!wrap) return;
  var out = wrap.querySelector('.vzx-r-readout');
  var idle = out ? out.textContent : '';
  function set(key) {
    wrap.querySelectorAll('.vzx-r-node, .vzx-r-row').forEach(function (el) {
      el.classList.toggle('is-on', !!key && el.dataset.track === key);
    });
    wrap.classList.toggle('is-focused', !!key);
    if (!out) return;
    if (!key) { out.textContent = idle; return; }
    var node = wrap.querySelector('.vzx-r-node[data-track="' + key + '"]');
    if (node) out.textContent = node.getAttribute('aria-label');
  }
  wrap.querySelectorAll('.vzx-r-node, .vzx-r-row').forEach(function (el) {
    var key = el.dataset.track;
    el.addEventListener('mouseenter', function () { set(key); });
    el.addEventListener('mouseleave', function () { set(null); });
    el.addEventListener('focusin', function () { set(key); });
    el.addEventListener('focusout', function () { set(null); });
  });
})();
(function () {
  // Suppress transitions for the frame the theme class flips in, so nothing
  // on the page tries to interpolate its colours.
  var root = document.documentElement;
  function guard() {
    root.classList.add('vz-swapping');
    requestAnimationFrame(function () {
      requestAnimationFrame(function () { root.classList.remove('vz-swapping'); });
    });
  }
  document.addEventListener('click', function (e) {
    if (e.target.closest && e.target.closest('#themeToggle, .theme-toggle')) guard();
  }, true);
})();
</script>"""


def main():
    src = open(INDEX, encoding="utf-8").read()
    n, tracks = counts(), track_data()

    removed = bool(INTRO_BAND.search(src))
    src = INTRO_BAND.sub("", src)
    src = TOP_BLOCK.sub("", src)
    src = BOT_BLOCK.sub("", src)

    top = "%s\n%s\n%s\n    " % (BEGIN_TOP, start_here(tracks), END_TOP)
    bottom = "%s\n%s%s%s%s\n%s\n%s\n    " % (
        BEGIN_BOT,
        tracks_section(tracks, n["modules"], n["tracks"]),
        how_it_works(), faq(), cta(n["modules"]), RADAR_JS, END_BOT)

    at = src.find(ANCHOR_TOP)
    if at == -1:
        raise SystemExit("anchor %r not found" % ANCHOR_TOP)
    src = src[:at] + top + src[at:]

    at = src.find(ANCHOR_BOT)
    if at == -1:
        raise SystemExit("anchor %r not found" % ANCHOR_BOT)
    src = src[:at] + bottom + src[at:]

    open(INDEX, "w", encoding="utf-8").write(src)
    print("hub sections    : start-here above the rails, chart/steps/questions below")
    print("intro band      : %s" % ("removed" if removed else "already gone"))
    print("numbers         : %d modules, %d tracks (from the catalog)"
          % (n["modules"], n["tracks"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
