#!/usr/bin/env python3
"""Place the two display-ad slots on every module page.

The site loaded the AdSense script on all 367 pages but carried no <ins>
units at all, which meant it depended entirely on Auto ads being switched on
in the account. This puts the placements in the pages themselves.

Both are written as marker blocks whether or not a slot ID exists yet. With
build_seo.AD_SLOTS empty the block is a comment and nothing renders; filling
in a slot ID and rebuilding turns the placement on. Doing it this way means
enabling ads later is a one-line change rather than another edit across 343
files, and it keeps the placements reviewable in one place.

Where they go:

    top     between the visualisation and the written article, in the gap
            after </main> and before the article section
    bottom  under the article, above the footer

Never inside a visualisation. about.html tells readers that ads never sit
inside a visualisation and never gate a page, and that has to stay true.

Written on every build; idempotent.
"""

import os
import re
import sys

from build_seo import ADSENSE_CLIENT, AD_SLOTS
from lib_catalog import ROOT, modules

BEGIN = "<!-- VIZLEARN:AD-%s:BEGIN (generated by tools/build_ads.py) -->"
END = "<!-- VIZLEARN:AD-%s:END -->"

# Where each placement attaches. The anchor is matched literally and the block
# is written immediately before it, so a page that has neither anchor is left
# alone rather than guessed at.
ANCHORS = {
    "TOP": "<!-- auto-article-vizlearn -->",
    "BOTTOM": "<!-- VIZLEARN:FOOTER:BEGIN",
}


def block(name, slot):
    """The marker block for one placement.

    Without a slot ID this is two markers and a note - no <ins>, because an
    <ins> carrying an invalid data-ad-slot logs an error on every page load
    and fills nothing.
    """
    lines = [BEGIN % name]
    if slot:
        lines += [
            '    <aside class="vz-ad" aria-label="Advertisement">',
            '        <ins class="adsbygoogle"',
            '             style="display:block"',
            '             data-ad-client="%s"' % ADSENSE_CLIENT,
            '             data-ad-slot="%s"' % slot,
            '             data-ad-format="auto"',
            '             data-full-width-responsive="true"></ins>',
            '        <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>',
            "    </aside>",
        ]
    else:
        lines.append("    <!-- placement reserved; set AD_SLOTS[%r] in "
                     "tools/build_seo.py to enable -->" % name.lower())
    lines.append(END % name)
    return "\n".join("    " + x if i else x
                     for i, x in enumerate(lines)) + "\n\n"


def apply(src, name, slot):
    """Insert or replace one placement. Returns the new source."""
    existing = re.compile(
        re.escape(BEGIN % name) + r".*?" + re.escape(END % name) + r"\n*", re.S)
    fresh = block(name, slot)
    if existing.search(src):
        return existing.sub(lambda _: fresh, src, count=1)
    anchor = ANCHORS[name]
    i = src.find(anchor)
    if i == -1:
        return src
    # Keep the anchor's own indentation on the block above it.
    line_start = src.rfind("\n", 0, i) + 1
    indent = src[line_start:i]
    return src[:line_start] + indent + fresh + src[line_start:]


def main():
    touched = 0
    for m in modules():
        path = os.path.join(ROOT, m["path"])
        if not os.path.exists(path):
            continue
        src = open(path, encoding="utf-8").read()
        out = src
        for name in ("TOP", "BOTTOM"):
            out = apply(out, name, AD_SLOTS.get(name.lower(), ""))
        if out != src:
            open(path, "w", encoding="utf-8").write(out)
            touched += 1
    live = [k for k, v in AD_SLOTS.items() if v]
    print("ad placements : %d pages, %s"
          % (touched, ", ".join(live) if live else "no slot IDs set (inert)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
