#!/usr/bin/env python3
"""Pre-render the hub's card grid into index.html.

The grid is built client-side from courseData. Googlebot runs JavaScript, but
Bing, LinkedIn, Slack, WhatsApp and most other crawlers do not - they saw an
empty <main>. This writes the same markup statically between markers, so the
166 module links are in the HTML source. The existing renderCourses() still
takes over on load and replaces it, so filtering and carousels are unaffected.

Idempotent: re-running replaces the block.
"""

import html
import os
import re

from lib_catalog import ROOT, read_course_data
from lib_pages import TOPIC_ORDER

INDEX = os.path.join(ROOT, "index.html")

BEGIN = "<!-- VIZLEARN:CARDS:BEGIN (generated by tools/build_prerender.py) -->"
END = "<!-- VIZLEARN:CARDS:END -->"

BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
PLACEHOLDER = re.compile(r"<!-- Courses will be injected here -->")


def card(course):
    """Link + title only.

    The card artwork is deliberately left out: it is decorative, it is the bulk
    of courseData's bytes, and renderCourses() paints it in a moment anyway.
    Crawlers need the href and the title, and inlining 166 SVGs here nearly
    doubled the transferred size of the homepage.
    """
    return (
        '<div class="course-wrapper group">'
        '<div class="card-container">'
        '<a href="%s" class="block">'
        '<div class="card-icon-area aspect-[16/9]"></div>'
        '<div class="px-4 py-4">'
        '<h3 class="card-title text-sm font-semibold leading-tight">%s</h3>'
        "</div></a></div></div>"
        % (html.escape(course["path"]), html.escape(course["title"]))
    )


def main():
    data, _, _ = read_course_data()

    # Same order the hub renders in (TRACK_ORDER in index.html, TOPIC_ORDER
    # here), so the copy a crawler sees matches the copy a reader sees rather
    # than following courseData's incidental key order. Unlisted keys still
    # render, at the end, so a new track can never be dropped silently.
    ordered = ([k for k in TOPIC_ORDER if k in data] +
               [k for k in data if k not in TOPIC_ORDER])

    sections = []
    total = 0
    for key in ordered:
        topic = data[key]
        cards = "".join(card(c) for c in topic["courses"])
        total += len(topic["courses"])
        sections.append(
            '<section class="course-section mb-12" data-topic="%s" id="%s">'
            '<div class="flex justify-between items-end mb-5 px-1 border-b border-green-500/10 pb-2">'
            '<div class="flex items-center gap-3">'
            '<div class="w-1 h-5 bg-green-500 rounded-full"></div>'
            '<h2 class="text-xl font-bold tracking-wide" style="color: var(--text-main)">%s</h2>'
            "</div></div>"
            '<div class="flex flex-nowrap overflow-x-auto space-x-5 pb-6 no-scrollbar carousel-wrapper">%s</div>'
            "</section>" % (key, key, html.escape(topic["title"]), cards)
        )

    block = (
        BEGIN
        + "\n<!-- Static copy of the card grid for crawlers that do not run JS.\n"
        "     renderCourses() replaces this on load; edit courseData, not this. -->\n"
        + "\n".join(sections)
        + "\n"
        + END
    )

    src = open(INDEX, encoding="utf-8").read()
    if BLOCK.search(src):
        src = BLOCK.sub(lambda _: block, src)
    elif PLACEHOLDER.search(src):
        src = PLACEHOLDER.sub(lambda _: block, src, count=1)
    else:
        raise SystemExit("no insertion point found in index.html")

    open(INDEX, "w", encoding="utf-8").write(src)
    print("pre-rendered %d cards across %d sections" % (total, len(sections)))


if __name__ == "__main__":
    main()
