#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Emit FAQPage JSON-LD from each article's "Questions people ask" section.

352 of the 635 articles end with a run of `<strong>Question?</strong> Answer`
pairs, and not one page declared them as structured data - so the answers the
articles already contain were invisible to the one rich result this site is
plainly entitled to. This reads the rendered page rather than the .txt, so it
works for the generated tracks and the hand-written ones alike, and it runs
after `codepaint` in the build chain.

    python3 tools/build_faq_schema.py                 # every page
    python3 tools/build_faq_schema.py dsa/stacks      # just one

Idempotent: the block sits between markers and is replaced, not appended.
"""

import glob
import html
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BEGIN = "<!-- VIZLEARN:FAQ:BEGIN (generated by tools/build_faq_schema.py) -->"
END = "<!-- VIZLEARN:FAQ:END -->"
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

# The Q&A run inside the section: a <strong> question, then prose until the
# next <strong> or the end of the block.
QA = re.compile(r"<strong>(.*?)</strong>(.*?)(?=<strong>|\Z)", re.S)
TAG = re.compile(r"<[^>]+>")

# The section heading, as the articles actually write it.
HEAD = re.compile(
    r'<h[2-4][^>]*>\s*(?:<[^>]+>\s*)*[^<]*?'
    r'(questions people ask|common questions|frequently asked)'
    r'[^<]*</h[2-4]>', re.I)


def text_of(frag):
    return html.unescape(TAG.sub(" ", frag)).replace(" ", " ")


def clean(s):
    s = re.sub(r"\s+", " ", s).strip()
    # Stripping inline <code> leaves a space before the punctuation that
    # followed it, so "text[::-1] ." and "bytes ?" come out of the tag pass.
    s = re.sub(r"\s+([.,;:?!])", r"\1", s)
    return s.strip(" -—:")


def questions(page_src):
    """[(question, answer)] from the page's Q&A section, or []."""
    m = HEAD.search(page_src)
    if not m:
        return []
    # The section runs to the next heading of the same or higher level.
    rest = page_src[m.end():]
    stop = re.search(r"<h[2-3]\b", rest)
    block = rest[:stop.start()] if stop else rest[:12000]
    out = []
    for q, a in QA.findall(block):
        q, a = clean(text_of(q)), clean(text_of(a))
        # A question mark is the cheap test that this <strong> is a question
        # and not one of the bolded lead-ins the articles also use. The
        # answer floor is deliberately low: "How do I reverse a string?"
        # is answered by `text[::-1]` and that is a complete answer.
        if not q or len(a) < 10:
            continue
        if not q.endswith("?"):
            continue
        out.append((q, a))
    return out


def render(qas, url):
    data = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "url": url,
        "mainEntity": [
            {"@type": "Question", "name": q,
             "acceptedAnswer": {"@type": "Answer", "text": a}}
            for q, a in qas
        ],
    }
    return "%s\n<script type=\"application/ld+json\">%s</script>\n%s" % (
        BEGIN, json.dumps(data, ensure_ascii=False), END)


def apply(rel):
    path = os.path.join(ROOT, rel)
    src = io.open(path, encoding="utf-8").read()
    src_clean = BLOCK.sub("", src)
    qas = questions(src_clean)
    if not qas:
        if src_clean != src:
            io.open(path, "w", encoding="utf-8").write(src_clean)
            return 0, "removed a stale block"
        return 0, None
    url = "https://vizlearn.in/" + rel
    block = render(qas, url)
    i = src_clean.find("</head>")
    if i < 0:
        return 0, "no </head>"
    out = src_clean[:i] + block + src_clean[i:]
    io.open(path, "w", encoding="utf-8").write(out)
    return len(qas), None


def main(argv):
    if argv:
        rels = [a.replace(".html", "") + ".html" for a in argv]
    else:
        # glob(root_dir=) is 3.10+; the build machine is 3.9.6.
        n = len(ROOT) + 1
        rels = sorted(p[n:] for p in glob.glob(os.path.join(ROOT, "*", "*.html"))
                      if not p.endswith("index.html"))
    pages = total = 0
    for rel in rels:
        if not os.path.exists(os.path.join(ROOT, rel)):
            print("  skip (not built): %s" % rel)
            continue
        n, note = apply(rel)
        if note:
            print("  %s: %s" % (rel, note))
        if n:
            pages += 1
            total += n
    print("FAQPage schema : %d pages, %d questions" % (pages, total))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
