/* Merge the 16 divergent inline `tailwind.config` blocks into one config.
 *
 * Each page used to ship its own config to the CDN compiler. Building a single
 * stylesheet means one config has to cover every page, so we union all the
 * custom colors / animations / keyframes and resolve the handful of conflicts
 * (same animation name, different duration) by majority page count.
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');

// Pages can be scanned from somewhere other than the working tree (e.g. a
// checkout of the originals), but the config is always written to ROOT.
const SCAN = process.argv[2] ? path.resolve(process.argv[2]) : ROOT;

function htmlFiles() {
  const out = [];
  const idx = path.join(SCAN, 'index.html');
  if (fs.existsSync(idx)) out.push(idx);
  for (const dir of fs.readdirSync(SCAN, { withFileTypes: true })) {
    if (!dir.isDirectory() || dir.name.startsWith('.') || ['tools', 'assets', 'node_modules'].includes(dir.name)) continue;
    for (const f of fs.readdirSync(path.join(SCAN, dir.name))) {
      if (f.endsWith('.html')) out.push(path.join(SCAN, dir.name, f));
    }
  }
  return out;
}

/** Return the balanced {...} literal starting at `start`, or null. */
function braceMatch(src, start) {
  if (start < 0) return null;
  let depth = 0;
  for (let i = start; i < src.length; i++) {
    const c = src[i];
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) return src.slice(start, i + 1);
    }
  }
  return null;
}

const colors = {};
const animation = {};   // name -> {value: count}
const keyframes = {};   // name -> {json: count}
let found = 0;

// Seed from any config already generated, so running this again after pages
// have had their inline configs stripped does not drop earlier findings.
const CONFIG_PATH = path.join(ROOT, 'tailwind.config.js');
if (fs.existsSync(CONFIG_PATH)) {
  const prev = require(CONFIG_PATH);
  const ext = (prev.theme && prev.theme.extend) || {};
  Object.assign(colors, ext.colors || {});
  for (const [k, v] of Object.entries(ext.animation || {})) animation[k] = { [v]: 1 };
  for (const [k, v] of Object.entries(ext.keyframes || {})) keyframes[k] = { [JSON.stringify(v)]: 1 };
  console.log('seeded from existing tailwind.config.js');
}

for (const file of htmlFiles()) {
  const src = fs.readFileSync(file, 'utf8');
  // Two shapes exist in the wild: a bare `tailwind.config = {...}`, and one
  // wrapped in an initTailwind() retry loop. Brace-match rather than regex so
  // both are handled.
  const at = src.indexOf('tailwind.config');
  if (at === -1) continue;
  const literal = braceMatch(src, src.indexOf('{', at));
  if (!literal) continue;
  let cfg;
  try {
    cfg = vm.runInNewContext('(' + literal + ')');
  } catch (e) {
    console.error('!! could not parse config in', path.relative(ROOT, file), e.message);
    continue;
  }
  found++;
  const ext = (cfg.theme && cfg.theme.extend) || {};
  Object.assign(colors, ext.colors && ext.colors.brand ? { brand: Object.assign(colors.brand || {}, ext.colors.brand) } : {});
  for (const [k, v] of Object.entries(ext.animation || {})) {
    animation[k] = animation[k] || {};
    animation[k][v] = (animation[k][v] || 0) + 1;
  }
  for (const [k, v] of Object.entries(ext.keyframes || {})) {
    const j = JSON.stringify(v);
    keyframes[k] = keyframes[k] || {};
    keyframes[k][j] = (keyframes[k][j] || 0) + 1;
  }
}

function winner(counts) {
  return Object.entries(counts).sort((a, b) => b[1] - a[1])[0];
}

const finalAnimation = {};
for (const [name, counts] of Object.entries(animation)) {
  const [value, n] = winner(counts);
  finalAnimation[name] = value;
  if (Object.keys(counts).length > 1) {
    console.log(`  conflict "${name}": chose ${JSON.stringify(value)} (${n} pages) over`,
      Object.keys(counts).filter((v) => v !== value).map((v) => JSON.stringify(v)).join(', '));
  }
}

const finalKeyframes = {};
for (const [name, counts] of Object.entries(keyframes)) {
  finalKeyframes[name] = JSON.parse(winner(counts)[0]);
}

const out = `/* GENERATED by tools/merge_tw_config.js - merged from ${found} inline page configs. */
module.exports = {
  darkMode: 'class',
  // './*.html' matters as much as the rest: about/contact/privacy/terms sit at
  // the repo root, and without it every class unique to them is purged.
  content: ['./*.html', './*/*.html', './assets/*.js'],
  theme: {
    extend: {
      colors: ${JSON.stringify(colors, null, 6).replace(/\n/g, '\n      ')},
      animation: ${JSON.stringify(finalAnimation, null, 6).replace(/\n/g, '\n      ')},
      keyframes: ${JSON.stringify(finalKeyframes, null, 6).replace(/\n/g, '\n      ')},
    },
  },
  plugins: [],
};
`;

fs.writeFileSync(path.join(ROOT, 'tailwind.config.js'), out);
console.log(`\nmerged ${found} configs -> tailwind.config.js`);
console.log('animations:', Object.keys(finalAnimation).join(', '));
console.log('keyframes :', Object.keys(finalKeyframes).join(', '));
